basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: romy@kreatif.id
    name: API Support
  description: API for Document Management System with AI and RFID support.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Kreatif DMS API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
