// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcements.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (title, message, notes, is_active, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, message, notes, is_active, created_at, updated_at, created_by
`

type CreateAnnouncementParams struct {
	Title     string      `json:"title"`
	Message   string      `json:"message"`
	Notes     pgtype.Text `json:"notes"`
	IsActive  bool        `json:"is_active"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.Title,
		arg.Message,
		arg.Notes,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deactivateAllAnnouncements = `-- name: DeactivateAllAnnouncements :exec
UPDATE announcements SET is_active = false WHERE is_active = true
`

func (q *Queries) DeactivateAllAnnouncements(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateAllAnnouncements)
	return err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :exec
DELETE FROM announcements WHERE id = $1
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnnouncement, id)
	return err
}

const getActiveAnnouncement = `-- name: GetActiveAnnouncement :one
SELECT id, title, message, notes, is_active, created_at, updated_at, created_by FROM announcements WHERE is_active = true ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetActiveAnnouncement(ctx context.Context) (Announcement, error) {
	row := q.db.QueryRow(ctx, getActiveAnnouncement)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getAnnouncement = `-- name: GetAnnouncement :one
SELECT id, title, message, notes, is_active, created_at, updated_at, created_by FROM announcements WHERE id = $1
`

func (q *Queries) GetAnnouncement(ctx context.Context, id uuid.UUID) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncement, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, title, message, notes, is_active, created_at, updated_at, created_by FROM announcements ORDER BY created_at DESC
`

// Announcements
func (q *Queries) ListAnnouncements(ctx context.Context) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Announcement
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
UPDATE announcements SET 
    title = $2, 
    message = $3, 
    notes = $4, 
    is_active = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, message, notes, is_active, created_at, updated_at, created_by
`

type UpdateAnnouncementParams struct {
	ID       uuid.UUID   `json:"id"`
	Title    string      `json:"title"`
	Message  string      `json:"message"`
	Notes    pgtype.Text `json:"notes"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement,
		arg.ID,
		arg.Title,
		arg.Message,
		arg.Notes,
		arg.IsActive,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}
