// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyStats = `-- name: GetDailyStats :one
SELECT 
    (SELECT COUNT(*) FROM documents WHERE created_at >= CURRENT_DATE) as daily_received,
    (SELECT COUNT(*) FROM ocr_jobs WHERE completed_at >= CURRENT_DATE AND status = 'completed') as daily_scanned,
    (SELECT COUNT(*) FROM documents WHERE updated_at >= CURRENT_DATE AND status = 'active') as daily_processed,
    (SELECT COALESCE(SUM(file_size), 0) FROM documents) as total_storage_size,
    (SELECT COUNT(*) FROM approval_workflows WHERE status = 'pending') as active_tasks
`

type GetDailyStatsRow struct {
	DailyReceived    int64       `json:"daily_received"`
	DailyScanned     int64       `json:"daily_scanned"`
	DailyProcessed   int64       `json:"daily_processed"`
	TotalStorageSize interface{} `json:"total_storage_size"`
	ActiveTasks      int64       `json:"active_tasks"`
}

func (q *Queries) GetDailyStats(ctx context.Context) (GetDailyStatsRow, error) {
	row := q.db.QueryRow(ctx, getDailyStats)
	var i GetDailyStatsRow
	err := row.Scan(
		&i.DailyReceived,
		&i.DailyScanned,
		&i.DailyProcessed,
		&i.TotalStorageSize,
		&i.ActiveTasks,
	)
	return i, err
}

const getPriorityTasks = `-- name: GetPriorityTasks :many
SELECT 
    id,
    entity_type,
    entity_id,
    level,
    status,
    created_at
FROM approval_workflows
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

type GetPriorityTasksRow struct {
	ID         uuid.UUID          `json:"id"`
	EntityType string             `json:"entity_type"`
	EntityID   uuid.UUID          `json:"entity_id"`
	Level      int32              `json:"level"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPriorityTasks(ctx context.Context, limit int32) ([]GetPriorityTasksRow, error) {
	rows, err := q.db.Query(ctx, getPriorityTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPriorityTasksRow
	for rows.Next() {
		var i GetPriorityTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Level,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentActivities = `-- name: GetRecentActivities :many
SELECT 
    a.id,
    a.action,
    a.entity_type,
    a.entity_id,
    a.details,
    a.created_at,
    u.full_name as user_name,
    u.email as user_email
FROM activity_logs a
JOIN users u ON a.user_id = u.id
ORDER BY a.created_at DESC
LIMIT $1
`

type GetRecentActivitiesRow struct {
	ID         uuid.UUID          `json:"id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Details    []byte             `json:"details"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UserName   string             `json:"user_name"`
	UserEmail  string             `json:"user_email"`
}

func (q *Queries) GetRecentActivities(ctx context.Context, limit int32) ([]GetRecentActivitiesRow, error) {
	rows, err := q.db.Query(ctx, getRecentActivities, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentActivitiesRow
	for rows.Next() {
		var i GetRecentActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
