// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBatch = `-- name: CreateBatch :one
INSERT INTO processing_batches (user_id, total_files) 
VALUES ($1, $2) RETURNING id, user_id, total_files, processed_files, status, created_at, updated_at
`

type CreateBatchParams struct {
	UserID     uuid.UUID `json:"user_id"`
	TotalFiles int32     `json:"total_files"`
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (ProcessingBatch, error) {
	row := q.db.QueryRow(ctx, createBatch, arg.UserID, arg.TotalFiles)
	var i ProcessingBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalFiles,
		&i.ProcessedFiles,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    title, description, file_name, file_path, file_size, mime_type, 
    company_id, branch_id, department_id, owner_id, status, batch_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, title, description, file_name, file_path, file_size, mime_type, checksum, company_id, branch_id, department_id, rack_id, box_id, ordner_id, owner_id, current_version, status, tags, metadata, extracted_text, is_ocr_processed, created_at, updated_at, batch_id
`

type CreateDocumentParams struct {
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	FileName     string      `json:"file_name"`
	FilePath     string      `json:"file_path"`
	FileSize     int64       `json:"file_size"`
	MimeType     string      `json:"mime_type"`
	CompanyID    uuid.UUID   `json:"company_id"`
	BranchID     uuid.UUID   `json:"branch_id"`
	DepartmentID uuid.UUID   `json:"department_id"`
	OwnerID      uuid.UUID   `json:"owner_id"`
	Status       string      `json:"status"`
	BatchID      pgtype.UUID `json:"batch_id"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.Title,
		arg.Description,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
		arg.MimeType,
		arg.CompanyID,
		arg.BranchID,
		arg.DepartmentID,
		arg.OwnerID,
		arg.Status,
		arg.BatchID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.Checksum,
		&i.CompanyID,
		&i.BranchID,
		&i.DepartmentID,
		&i.RackID,
		&i.BoxID,
		&i.OrdnerID,
		&i.OwnerID,
		&i.CurrentVersion,
		&i.Status,
		&i.Tags,
		&i.Metadata,
		&i.ExtractedText,
		&i.IsOcrProcessed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BatchID,
	)
	return i, err
}

const getBatch = `-- name: GetBatch :one
SELECT id, user_id, total_files, processed_files, status, created_at, updated_at FROM processing_batches WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBatch(ctx context.Context, id uuid.UUID) (ProcessingBatch, error) {
	row := q.db.QueryRow(ctx, getBatch, id)
	var i ProcessingBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalFiles,
		&i.ProcessedFiles,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, title, description, file_name, file_path, file_size, mime_type, checksum, company_id, branch_id, department_id, rack_id, box_id, ordner_id, owner_id, current_version, status, tags, metadata, extracted_text, is_ocr_processed, created_at, updated_at, batch_id FROM documents WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.Checksum,
		&i.CompanyID,
		&i.BranchID,
		&i.DepartmentID,
		&i.RackID,
		&i.BoxID,
		&i.OrdnerID,
		&i.OwnerID,
		&i.CurrentVersion,
		&i.Status,
		&i.Tags,
		&i.Metadata,
		&i.ExtractedText,
		&i.IsOcrProcessed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BatchID,
	)
	return i, err
}

const getDocumentsByBatch = `-- name: GetDocumentsByBatch :many
SELECT id, title, description, file_name, file_path, file_size, mime_type, checksum, company_id, branch_id, department_id, rack_id, box_id, ordner_id, owner_id, current_version, status, tags, metadata, extracted_text, is_ocr_processed, created_at, updated_at, batch_id FROM documents WHERE batch_id = $1
`

func (q *Queries) GetDocumentsByBatch(ctx context.Context, batchID pgtype.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocumentsByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.Checksum,
			&i.CompanyID,
			&i.BranchID,
			&i.DepartmentID,
			&i.RackID,
			&i.BoxID,
			&i.OrdnerID,
			&i.OwnerID,
			&i.CurrentVersion,
			&i.Status,
			&i.Tags,
			&i.Metadata,
			&i.ExtractedText,
			&i.IsOcrProcessed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByDepartment = `-- name: ListDocumentsByDepartment :many
SELECT id, title, description, file_name, file_path, file_size, mime_type, checksum, company_id, branch_id, department_id, rack_id, box_id, ordner_id, owner_id, current_version, status, tags, metadata, extracted_text, is_ocr_processed, created_at, updated_at, batch_id FROM documents 
WHERE department_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByDepartment(ctx context.Context, departmentID uuid.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByDepartment, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.Checksum,
			&i.CompanyID,
			&i.BranchID,
			&i.DepartmentID,
			&i.RackID,
			&i.BoxID,
			&i.OrdnerID,
			&i.OwnerID,
			&i.CurrentVersion,
			&i.Status,
			&i.Tags,
			&i.Metadata,
			&i.ExtractedText,
			&i.IsOcrProcessed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBatchProgress = `-- name: UpdateBatchProgress :exec
UPDATE processing_batches 
SET processed_files = processed_files + 1, 
    status = CASE WHEN processed_files + 1 >= total_files THEN 'completed' ELSE 'processing' END,
    updated_at = NOW() 
WHERE id = $1
`

func (q *Queries) UpdateBatchProgress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateBatchProgress, id)
	return err
}

const updateDocumentMetadata = `-- name: UpdateDocumentMetadata :exec
UPDATE documents 
SET metadata = $2, updated_at = NOW() 
WHERE id = $1
`

type UpdateDocumentMetadataParams struct {
	ID       uuid.UUID `json:"id"`
	Metadata []byte    `json:"metadata"`
}

func (q *Queries) UpdateDocumentMetadata(ctx context.Context, arg UpdateDocumentMetadataParams) error {
	_, err := q.db.Exec(ctx, updateDocumentMetadata, arg.ID, arg.Metadata)
	return err
}

const updateDocumentOCR = `-- name: UpdateDocumentOCR :exec
UPDATE documents 
SET extracted_text = $2, 
    metadata = $3,
    is_ocr_processed = true, 
    status = 'active', 
    updated_at = NOW() 
WHERE id = $1
`

type UpdateDocumentOCRParams struct {
	ID            uuid.UUID   `json:"id"`
	ExtractedText pgtype.Text `json:"extracted_text"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) UpdateDocumentOCR(ctx context.Context, arg UpdateDocumentOCRParams) error {
	_, err := q.db.Exec(ctx, updateDocumentOCR, arg.ID, arg.ExtractedText, arg.Metadata)
	return err
}
