// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOCRJobs = `-- name: CountOCRJobs :one
SELECT COUNT(*) FROM ocr_jobs
`

func (q *Queries) CountOCRJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOCRJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBatch = `-- name: CreateBatch :one
INSERT INTO processing_batches (user_id, total_files) 
VALUES ($1, $2) RETURNING id, user_id, total_files, processed_files, status, created_at, updated_at, intake_session_id, department_id
`

type CreateBatchParams struct {
	UserID     uuid.UUID `json:"user_id"`
	TotalFiles int32     `json:"total_files"`
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (ProcessingBatch, error) {
	row := q.db.QueryRow(ctx, createBatch, arg.UserID, arg.TotalFiles)
	var i ProcessingBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalFiles,
		&i.ProcessedFiles,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IntakeSessionID,
		&i.DepartmentID,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    title, description, file_name, file_path, file_size, mime_type, 
    company_id, branch_id, department_id, owner_id, status, batch_id,
    sensitivity, metadata, type_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, title, description, file_name, file_path, file_size, mime_type, checksum, company_id, branch_id, department_id, rack_id, box_id, ordner_id, owner_id, current_version, status, tags, metadata, extracted_text, is_ocr_processed, created_at, updated_at, batch_id, retention_years, retention_expiry_date, sensitivity, circulation_id, minio_bucket, es_indexed, type_id, current_manifest_id, physical_status
`

type CreateDocumentParams struct {
	Title        string          `json:"title"`
	Description  pgtype.Text     `json:"description"`
	FileName     pgtype.Text     `json:"file_name"`
	FilePath     pgtype.Text     `json:"file_path"`
	FileSize     pgtype.Int8     `json:"file_size"`
	MimeType     pgtype.Text     `json:"mime_type"`
	CompanyID    uuid.UUID       `json:"company_id"`
	BranchID     uuid.UUID       `json:"branch_id"`
	DepartmentID uuid.UUID       `json:"department_id"`
	OwnerID      uuid.UUID       `json:"owner_id"`
	Status       string          `json:"status"`
	BatchID      pgtype.UUID     `json:"batch_id"`
	Sensitivity  pgtype.Text     `json:"sensitivity"`
	Metadata     json.RawMessage `json:"metadata"`
	TypeID       pgtype.UUID     `json:"type_id"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.Title,
		arg.Description,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
		arg.MimeType,
		arg.CompanyID,
		arg.BranchID,
		arg.DepartmentID,
		arg.OwnerID,
		arg.Status,
		arg.BatchID,
		arg.Sensitivity,
		arg.Metadata,
		arg.TypeID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.Checksum,
		&i.CompanyID,
		&i.BranchID,
		&i.DepartmentID,
		&i.RackID,
		&i.BoxID,
		&i.OrdnerID,
		&i.OwnerID,
		&i.CurrentVersion,
		&i.Status,
		&i.Tags,
		&i.Metadata,
		&i.ExtractedText,
		&i.IsOcrProcessed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BatchID,
		&i.RetentionYears,
		&i.RetentionExpiryDate,
		&i.Sensitivity,
		&i.CirculationID,
		&i.MinioBucket,
		&i.EsIndexed,
		&i.TypeID,
		&i.CurrentManifestID,
		&i.PhysicalStatus,
	)
	return i, err
}

const createOCRJob = `-- name: CreateOCRJob :one
INSERT INTO ocr_jobs (
    entity_type, entity_id, ocr_service_url, ocr_engine, 
    source_file_path, raw_text, word_count, confidence_avg, words_json,
    status, processing_time_ms, preview_path, preview_paths, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW()
) RETURNING id, entity_type, entity_id, ocr_service_url, ocr_engine, source_file_path, source_pages, raw_text, word_count, confidence_avg, words_json, ai_provider, ai_refined_text, ai_metadata, ai_refinement_status, status, error_message, processing_time_ms, async_task_id, created_at, completed_at, preview_path, preview_paths
`

type CreateOCRJobParams struct {
	EntityType       string          `json:"entity_type"`
	EntityID         uuid.UUID       `json:"entity_id"`
	OcrServiceUrl    pgtype.Text     `json:"ocr_service_url"`
	OcrEngine        pgtype.Text     `json:"ocr_engine"`
	SourceFilePath   pgtype.Text     `json:"source_file_path"`
	RawText          pgtype.Text     `json:"raw_text"`
	WordCount        pgtype.Int4     `json:"word_count"`
	ConfidenceAvg    pgtype.Numeric  `json:"confidence_avg"`
	WordsJson        json.RawMessage `json:"words_json"`
	Status           string          `json:"status"`
	ProcessingTimeMs pgtype.Int4     `json:"processing_time_ms"`
	PreviewPath      pgtype.Text     `json:"preview_path"`
	PreviewPaths     []byte          `json:"preview_paths"`
}

func (q *Queries) CreateOCRJob(ctx context.Context, arg CreateOCRJobParams) (OcrJob, error) {
	row := q.db.QueryRow(ctx, createOCRJob,
		arg.EntityType,
		arg.EntityID,
		arg.OcrServiceUrl,
		arg.OcrEngine,
		arg.SourceFilePath,
		arg.RawText,
		arg.WordCount,
		arg.ConfidenceAvg,
		arg.WordsJson,
		arg.Status,
		arg.ProcessingTimeMs,
		arg.PreviewPath,
		arg.PreviewPaths,
	)
	var i OcrJob
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.OcrServiceUrl,
		&i.OcrEngine,
		&i.SourceFilePath,
		&i.SourcePages,
		&i.RawText,
		&i.WordCount,
		&i.ConfidenceAvg,
		&i.WordsJson,
		&i.AiProvider,
		&i.AiRefinedText,
		&i.AiMetadata,
		&i.AiRefinementStatus,
		&i.Status,
		&i.ErrorMessage,
		&i.ProcessingTimeMs,
		&i.AsyncTaskID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.PreviewPath,
		&i.PreviewPaths,
	)
	return i, err
}

const getBatch = `-- name: GetBatch :one
SELECT id, user_id, total_files, processed_files, status, created_at, updated_at, intake_session_id, department_id FROM processing_batches WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBatch(ctx context.Context, id uuid.UUID) (ProcessingBatch, error) {
	row := q.db.QueryRow(ctx, getBatch, id)
	var i ProcessingBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalFiles,
		&i.ProcessedFiles,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IntakeSessionID,
		&i.DepartmentID,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT d.id, d.title, d.description, d.file_name, d.file_path, d.file_size, d.mime_type, d.checksum, d.company_id, d.branch_id, d.department_id, d.rack_id, d.box_id, d.ordner_id, d.owner_id, d.current_version, d.status, d.tags, d.metadata, d.extracted_text, d.is_ocr_processed, d.created_at, d.updated_at, d.batch_id, d.retention_years, d.retention_expiry_date, d.sensitivity, d.circulation_id, d.minio_bucket, d.es_indexed, d.type_id, d.current_manifest_id, d.physical_status, dt.name as type_name
FROM documents d
LEFT JOIN document_types dt ON d.type_id = dt.id
WHERE d.id = $1 LIMIT 1
`

type GetDocumentRow struct {
	ID                  uuid.UUID          `json:"id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	FileName            pgtype.Text        `json:"file_name"`
	FilePath            pgtype.Text        `json:"file_path"`
	FileSize            pgtype.Int8        `json:"file_size"`
	MimeType            pgtype.Text        `json:"mime_type"`
	Checksum            pgtype.Text        `json:"checksum"`
	CompanyID           uuid.UUID          `json:"company_id"`
	BranchID            uuid.UUID          `json:"branch_id"`
	DepartmentID        uuid.UUID          `json:"department_id"`
	RackID              pgtype.UUID        `json:"rack_id"`
	BoxID               pgtype.UUID        `json:"box_id"`
	OrdnerID            pgtype.UUID        `json:"ordner_id"`
	OwnerID             uuid.UUID          `json:"owner_id"`
	CurrentVersion      int32              `json:"current_version"`
	Status              string             `json:"status"`
	Tags                []string           `json:"tags"`
	Metadata            json.RawMessage    `json:"metadata"`
	ExtractedText       pgtype.Text        `json:"extracted_text"`
	IsOcrProcessed      pgtype.Bool        `json:"is_ocr_processed"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	BatchID             pgtype.UUID        `json:"batch_id"`
	RetentionYears      pgtype.Int4        `json:"retention_years"`
	RetentionExpiryDate pgtype.Date        `json:"retention_expiry_date"`
	Sensitivity         pgtype.Text        `json:"sensitivity"`
	CirculationID       pgtype.UUID        `json:"circulation_id"`
	MinioBucket         pgtype.Text        `json:"minio_bucket"`
	EsIndexed           pgtype.Bool        `json:"es_indexed"`
	TypeID              pgtype.UUID        `json:"type_id"`
	CurrentManifestID   pgtype.UUID        `json:"current_manifest_id"`
	PhysicalStatus      pgtype.Text        `json:"physical_status"`
	TypeName            pgtype.Text        `json:"type_name"`
}

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.Checksum,
		&i.CompanyID,
		&i.BranchID,
		&i.DepartmentID,
		&i.RackID,
		&i.BoxID,
		&i.OrdnerID,
		&i.OwnerID,
		&i.CurrentVersion,
		&i.Status,
		&i.Tags,
		&i.Metadata,
		&i.ExtractedText,
		&i.IsOcrProcessed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BatchID,
		&i.RetentionYears,
		&i.RetentionExpiryDate,
		&i.Sensitivity,
		&i.CirculationID,
		&i.MinioBucket,
		&i.EsIndexed,
		&i.TypeID,
		&i.CurrentManifestID,
		&i.PhysicalStatus,
		&i.TypeName,
	)
	return i, err
}

const getDocumentLoanHistory = `-- name: GetDocumentLoanHistory :many
SELECT 
    br.id,
    u.full_name as user_name,
    u.department_id,
    dept.name as department_name,
    br.borrow_date,
    br.return_date,
    br.status,
    COALESCE(br.reason, '')::text as reason
FROM borrow_requests br
JOIN users u ON br.user_id = u.id
LEFT JOIN departments dept ON u.department_id = dept.id
WHERE br.document_id = $1
ORDER BY br.created_at DESC
`

type GetDocumentLoanHistoryRow struct {
	ID             uuid.UUID          `json:"id"`
	UserName       string             `json:"user_name"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	DepartmentName pgtype.Text        `json:"department_name"`
	BorrowDate     pgtype.Timestamptz `json:"borrow_date"`
	ReturnDate     pgtype.Timestamptz `json:"return_date"`
	Status         string             `json:"status"`
	Reason         string             `json:"reason"`
}

func (q *Queries) GetDocumentLoanHistory(ctx context.Context, documentID uuid.UUID) ([]GetDocumentLoanHistoryRow, error) {
	rows, err := q.db.Query(ctx, getDocumentLoanHistory, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentLoanHistoryRow
	for rows.Next() {
		var i GetDocumentLoanHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.DepartmentID,
			&i.DepartmentName,
			&i.BorrowDate,
			&i.ReturnDate,
			&i.Status,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentWithDetails = `-- name: GetDocumentWithDetails :one
SELECT 
    d.id, d.title, d.description, d.file_name, d.file_path, d.file_size, d.mime_type, d.checksum, d.company_id, d.branch_id, d.department_id, d.rack_id, d.box_id, d.ordner_id, d.owner_id, d.current_version, d.status, d.tags, d.metadata, d.extracted_text, d.is_ocr_processed, d.created_at, d.updated_at, d.batch_id, d.retention_years, d.retention_expiry_date, d.sensitivity, d.circulation_id, d.minio_bucket, d.es_indexed, d.type_id, d.current_manifest_id, d.physical_status,
    dt.name as type_name,
    c.name as company_name,
    b.name as branch_name,
    dept.name as department_name,
    r.name as rack_name,
    bx.name as box_name,
    o.name as ordner_name,
    u.full_name as owner_name,
    aw.rejection_reason,
    aw.decision_note as rejection_notes
FROM documents d
LEFT JOIN document_types dt ON d.type_id = dt.id
LEFT JOIN companies c ON d.company_id = c.id
LEFT JOIN branches b ON d.branch_id = b.id
LEFT JOIN departments dept ON d.department_id = dept.id
LEFT JOIN racks r ON d.rack_id = r.id
LEFT JOIN boxes bx ON d.box_id = bx.id
LEFT JOIN ordners o ON d.ordner_id = o.id
LEFT JOIN users u ON d.owner_id = u.id
LEFT JOIN LATERAL (
    SELECT rejection_reason, decision_note 
    FROM approval_workflows 
    WHERE entity_id = d.id AND status = 'rejected' 
    ORDER BY created_at DESC LIMIT 1
) aw ON TRUE
WHERE d.id = $1 LIMIT 1
`

type GetDocumentWithDetailsRow struct {
	ID                  uuid.UUID          `json:"id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	FileName            pgtype.Text        `json:"file_name"`
	FilePath            pgtype.Text        `json:"file_path"`
	FileSize            pgtype.Int8        `json:"file_size"`
	MimeType            pgtype.Text        `json:"mime_type"`
	Checksum            pgtype.Text        `json:"checksum"`
	CompanyID           uuid.UUID          `json:"company_id"`
	BranchID            uuid.UUID          `json:"branch_id"`
	DepartmentID        uuid.UUID          `json:"department_id"`
	RackID              pgtype.UUID        `json:"rack_id"`
	BoxID               pgtype.UUID        `json:"box_id"`
	OrdnerID            pgtype.UUID        `json:"ordner_id"`
	OwnerID             uuid.UUID          `json:"owner_id"`
	CurrentVersion      int32              `json:"current_version"`
	Status              string             `json:"status"`
	Tags                []string           `json:"tags"`
	Metadata            json.RawMessage    `json:"metadata"`
	ExtractedText       pgtype.Text        `json:"extracted_text"`
	IsOcrProcessed      pgtype.Bool        `json:"is_ocr_processed"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	BatchID             pgtype.UUID        `json:"batch_id"`
	RetentionYears      pgtype.Int4        `json:"retention_years"`
	RetentionExpiryDate pgtype.Date        `json:"retention_expiry_date"`
	Sensitivity         pgtype.Text        `json:"sensitivity"`
	CirculationID       pgtype.UUID        `json:"circulation_id"`
	MinioBucket         pgtype.Text        `json:"minio_bucket"`
	EsIndexed           pgtype.Bool        `json:"es_indexed"`
	TypeID              pgtype.UUID        `json:"type_id"`
	CurrentManifestID   pgtype.UUID        `json:"current_manifest_id"`
	PhysicalStatus      pgtype.Text        `json:"physical_status"`
	TypeName            pgtype.Text        `json:"type_name"`
	CompanyName         pgtype.Text        `json:"company_name"`
	BranchName          pgtype.Text        `json:"branch_name"`
	DepartmentName      pgtype.Text        `json:"department_name"`
	RackName            pgtype.Text        `json:"rack_name"`
	BoxName             pgtype.Text        `json:"box_name"`
	OrdnerName          pgtype.Text        `json:"ordner_name"`
	OwnerName           pgtype.Text        `json:"owner_name"`
	RejectionReason     pgtype.Text        `json:"rejection_reason"`
	RejectionNotes      pgtype.Text        `json:"rejection_notes"`
}

func (q *Queries) GetDocumentWithDetails(ctx context.Context, id uuid.UUID) (GetDocumentWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getDocumentWithDetails, id)
	var i GetDocumentWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.Checksum,
		&i.CompanyID,
		&i.BranchID,
		&i.DepartmentID,
		&i.RackID,
		&i.BoxID,
		&i.OrdnerID,
		&i.OwnerID,
		&i.CurrentVersion,
		&i.Status,
		&i.Tags,
		&i.Metadata,
		&i.ExtractedText,
		&i.IsOcrProcessed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BatchID,
		&i.RetentionYears,
		&i.RetentionExpiryDate,
		&i.Sensitivity,
		&i.CirculationID,
		&i.MinioBucket,
		&i.EsIndexed,
		&i.TypeID,
		&i.CurrentManifestID,
		&i.PhysicalStatus,
		&i.TypeName,
		&i.CompanyName,
		&i.BranchName,
		&i.DepartmentName,
		&i.RackName,
		&i.BoxName,
		&i.OrdnerName,
		&i.OwnerName,
		&i.RejectionReason,
		&i.RejectionNotes,
	)
	return i, err
}

const getDocumentsByBatch = `-- name: GetDocumentsByBatch :many
SELECT id, title, description, file_name, file_path, file_size, mime_type, checksum, company_id, branch_id, department_id, rack_id, box_id, ordner_id, owner_id, current_version, status, tags, metadata, extracted_text, is_ocr_processed, created_at, updated_at, batch_id, retention_years, retention_expiry_date, sensitivity, circulation_id, minio_bucket, es_indexed, type_id, current_manifest_id, physical_status FROM documents WHERE batch_id = $1
`

func (q *Queries) GetDocumentsByBatch(ctx context.Context, batchID pgtype.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocumentsByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.Checksum,
			&i.CompanyID,
			&i.BranchID,
			&i.DepartmentID,
			&i.RackID,
			&i.BoxID,
			&i.OrdnerID,
			&i.OwnerID,
			&i.CurrentVersion,
			&i.Status,
			&i.Tags,
			&i.Metadata,
			&i.ExtractedText,
			&i.IsOcrProcessed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BatchID,
			&i.RetentionYears,
			&i.RetentionExpiryDate,
			&i.Sensitivity,
			&i.CirculationID,
			&i.MinioBucket,
			&i.EsIndexed,
			&i.TypeID,
			&i.CurrentManifestID,
			&i.PhysicalStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOCRJobByEntity = `-- name: GetOCRJobByEntity :one
SELECT id, entity_type, entity_id, ocr_service_url, ocr_engine, source_file_path, source_pages, raw_text, word_count, confidence_avg, words_json, ai_provider, ai_refined_text, ai_metadata, ai_refinement_status, status, error_message, processing_time_ms, async_task_id, created_at, completed_at, preview_path, preview_paths FROM ocr_jobs
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetOCRJobByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) GetOCRJobByEntity(ctx context.Context, arg GetOCRJobByEntityParams) (OcrJob, error) {
	row := q.db.QueryRow(ctx, getOCRJobByEntity, arg.EntityType, arg.EntityID)
	var i OcrJob
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.OcrServiceUrl,
		&i.OcrEngine,
		&i.SourceFilePath,
		&i.SourcePages,
		&i.RawText,
		&i.WordCount,
		&i.ConfidenceAvg,
		&i.WordsJson,
		&i.AiProvider,
		&i.AiRefinedText,
		&i.AiMetadata,
		&i.AiRefinementStatus,
		&i.Status,
		&i.ErrorMessage,
		&i.ProcessingTimeMs,
		&i.AsyncTaskID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.PreviewPath,
		&i.PreviewPaths,
	)
	return i, err
}

const listDocumentsByDepartment = `-- name: ListDocumentsByDepartment :many
SELECT id, title, description, file_name, file_path, file_size, mime_type, checksum, company_id, branch_id, department_id, rack_id, box_id, ordner_id, owner_id, current_version, status, tags, metadata, extracted_text, is_ocr_processed, created_at, updated_at, batch_id, retention_years, retention_expiry_date, sensitivity, circulation_id, minio_bucket, es_indexed, type_id, current_manifest_id, physical_status FROM documents 
WHERE department_id = $1 AND status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByDepartment(ctx context.Context, departmentID uuid.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByDepartment, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.Checksum,
			&i.CompanyID,
			&i.BranchID,
			&i.DepartmentID,
			&i.RackID,
			&i.BoxID,
			&i.OrdnerID,
			&i.OwnerID,
			&i.CurrentVersion,
			&i.Status,
			&i.Tags,
			&i.Metadata,
			&i.ExtractedText,
			&i.IsOcrProcessed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BatchID,
			&i.RetentionYears,
			&i.RetentionExpiryDate,
			&i.Sensitivity,
			&i.CirculationID,
			&i.MinioBucket,
			&i.EsIndexed,
			&i.TypeID,
			&i.CurrentManifestID,
			&i.PhysicalStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOCRJobs = `-- name: ListOCRJobs :many
SELECT 
    j.id,
    j.entity_id,
    j.status,
    j.processing_time_ms,
    j.confidence_avg,
    j.preview_path,
    j.created_at,
    COALESCE(d.file_name, j.source_file_path) as filename,
    COALESCE(d.file_size, 0)::bigint as file_size,
    u.full_name as owner_name
FROM ocr_jobs j
LEFT JOIN documents d ON j.entity_id = d.id
LEFT JOIN users u ON d.owner_id = u.id
ORDER BY j.created_at DESC
LIMIT $1 OFFSET $2
`

type ListOCRJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListOCRJobsRow struct {
	ID               uuid.UUID          `json:"id"`
	EntityID         uuid.UUID          `json:"entity_id"`
	Status           string             `json:"status"`
	ProcessingTimeMs pgtype.Int4        `json:"processing_time_ms"`
	ConfidenceAvg    pgtype.Numeric     `json:"confidence_avg"`
	PreviewPath      pgtype.Text        `json:"preview_path"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Filename         pgtype.Text        `json:"filename"`
	FileSize         int64              `json:"file_size"`
	OwnerName        pgtype.Text        `json:"owner_name"`
}

func (q *Queries) ListOCRJobs(ctx context.Context, arg ListOCRJobsParams) ([]ListOCRJobsRow, error) {
	rows, err := q.db.Query(ctx, listOCRJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOCRJobsRow
	for rows.Next() {
		var i ListOCRJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.Status,
			&i.ProcessingTimeMs,
			&i.ConfidenceAvg,
			&i.PreviewPath,
			&i.CreatedAt,
			&i.Filename,
			&i.FileSize,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDocuments = `-- name: ListRecentDocuments :many
SELECT 
    d.id, d.title, d.status, d.created_at, d.mime_type, d.file_size, d.metadata,
    dt.name as type_name,
    dept.name as department_name,
    COALESCE(d.description, '')::text as category
FROM documents d
LEFT JOIN document_types dt ON d.type_id = dt.id
LEFT JOIN departments dept ON d.department_id = dept.id
WHERE d.status = 'active'
ORDER BY d.created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentDocumentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListRecentDocumentsRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	MimeType       pgtype.Text        `json:"mime_type"`
	FileSize       pgtype.Int8        `json:"file_size"`
	Metadata       json.RawMessage    `json:"metadata"`
	TypeName       pgtype.Text        `json:"type_name"`
	DepartmentName pgtype.Text        `json:"department_name"`
	Category       string             `json:"category"`
}

func (q *Queries) ListRecentDocuments(ctx context.Context, arg ListRecentDocumentsParams) ([]ListRecentDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listRecentDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentDocumentsRow
	for rows.Next() {
		var i ListRecentDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.MimeType,
			&i.FileSize,
			&i.Metadata,
			&i.TypeName,
			&i.DepartmentName,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDocumentsByOwner = `-- name: ListRecentDocumentsByOwner :many
SELECT 
    d.id, d.title, d.status, d.created_at, d.mime_type, d.file_size, d.metadata,
    dt.name as type_name,
    dept.name as department_name,
    COALESCE(d.description, '')::text as category
FROM documents d
LEFT JOIN document_types dt ON d.type_id = dt.id
LEFT JOIN departments dept ON d.department_id = dept.id
WHERE d.owner_id = $1
ORDER BY d.created_at DESC
LIMIT $2 OFFSET $3
`

type ListRecentDocumentsByOwnerParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListRecentDocumentsByOwnerRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	MimeType       pgtype.Text        `json:"mime_type"`
	FileSize       pgtype.Int8        `json:"file_size"`
	Metadata       json.RawMessage    `json:"metadata"`
	TypeName       pgtype.Text        `json:"type_name"`
	DepartmentName pgtype.Text        `json:"department_name"`
	Category       string             `json:"category"`
}

func (q *Queries) ListRecentDocumentsByOwner(ctx context.Context, arg ListRecentDocumentsByOwnerParams) ([]ListRecentDocumentsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listRecentDocumentsByOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentDocumentsByOwnerRow
	for rows.Next() {
		var i ListRecentDocumentsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.MimeType,
			&i.FileSize,
			&i.Metadata,
			&i.TypeName,
			&i.DepartmentName,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBatchProgress = `-- name: UpdateBatchProgress :exec
UPDATE processing_batches 
SET processed_files = processed_files + 1, 
    status = CASE WHEN processed_files + 1 >= total_files THEN 'completed' ELSE 'processing' END,
    updated_at = NOW() 
WHERE id = $1
`

func (q *Queries) UpdateBatchProgress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateBatchProgress, id)
	return err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents 
SET title = $2, 
    description = $3,
    type_id = $4,
    sensitivity = $5,
    metadata = $6,
    file_name = COALESCE(NULLIF($7::text, ''), file_name),
    file_path = COALESCE(NULLIF($8::text, ''), file_path),
    file_size = CASE WHEN $9::bigint > 0 THEN $9::bigint ELSE file_size END,
    mime_type = COALESCE(NULLIF($10::text, ''), mime_type),
    status = COALESCE(NULLIF($11::text, ''), 'pending'),
    updated_at = NOW() 
WHERE id = $1 
RETURNING id, title, description, file_name, file_path, file_size, mime_type, checksum, company_id, branch_id, department_id, rack_id, box_id, ordner_id, owner_id, current_version, status, tags, metadata, extracted_text, is_ocr_processed, created_at, updated_at, batch_id, retention_years, retention_expiry_date, sensitivity, circulation_id, minio_bucket, es_indexed, type_id, current_manifest_id, physical_status
`

type UpdateDocumentParams struct {
	ID          uuid.UUID       `json:"id"`
	Title       string          `json:"title"`
	Description pgtype.Text     `json:"description"`
	TypeID      pgtype.UUID     `json:"type_id"`
	Sensitivity pgtype.Text     `json:"sensitivity"`
	Metadata    json.RawMessage `json:"metadata"`
	FileName    string          `json:"file_name"`
	FilePath    string          `json:"file_path"`
	FileSize    int64           `json:"file_size"`
	MimeType    string          `json:"mime_type"`
	Status      string          `json:"status"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.TypeID,
		arg.Sensitivity,
		arg.Metadata,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
		arg.MimeType,
		arg.Status,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.Checksum,
		&i.CompanyID,
		&i.BranchID,
		&i.DepartmentID,
		&i.RackID,
		&i.BoxID,
		&i.OrdnerID,
		&i.OwnerID,
		&i.CurrentVersion,
		&i.Status,
		&i.Tags,
		&i.Metadata,
		&i.ExtractedText,
		&i.IsOcrProcessed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BatchID,
		&i.RetentionYears,
		&i.RetentionExpiryDate,
		&i.Sensitivity,
		&i.CirculationID,
		&i.MinioBucket,
		&i.EsIndexed,
		&i.TypeID,
		&i.CurrentManifestID,
		&i.PhysicalStatus,
	)
	return i, err
}

const updateDocumentMetadata = `-- name: UpdateDocumentMetadata :exec
UPDATE documents 
SET metadata = $2, updated_at = NOW() 
WHERE id = $1
`

type UpdateDocumentMetadataParams struct {
	ID       uuid.UUID       `json:"id"`
	Metadata json.RawMessage `json:"metadata"`
}

func (q *Queries) UpdateDocumentMetadata(ctx context.Context, arg UpdateDocumentMetadataParams) error {
	_, err := q.db.Exec(ctx, updateDocumentMetadata, arg.ID, arg.Metadata)
	return err
}

const updateDocumentOCR = `-- name: UpdateDocumentOCR :exec
UPDATE documents 
SET extracted_text = $2, 
    metadata = $3,
    is_ocr_processed = true, 
    status = 'pending', 
    updated_at = NOW() 
WHERE id = $1
`

type UpdateDocumentOCRParams struct {
	ID            uuid.UUID       `json:"id"`
	ExtractedText pgtype.Text     `json:"extracted_text"`
	Metadata      json.RawMessage `json:"metadata"`
}

func (q *Queries) UpdateDocumentOCR(ctx context.Context, arg UpdateDocumentOCRParams) error {
	_, err := q.db.Exec(ctx, updateDocumentOCR, arg.ID, arg.ExtractedText, arg.Metadata)
	return err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :exec
UPDATE documents 
SET status = $2, updated_at = NOW() 
WHERE id = $1
`

type UpdateDocumentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDocumentStatus, arg.ID, arg.Status)
	return err
}

const updateTaskStatusByEntity = `-- name: UpdateTaskStatusByEntity :exec
UPDATE approval_workflows 
SET status = $2,
    decided_at = NULL,
    decision_note = NULL,
    rejection_reason = NULL,
    updated_at = NOW()
WHERE entity_id = $1
`

type UpdateTaskStatusByEntityParams struct {
	EntityID uuid.UUID `json:"entity_id"`
	Status   string    `json:"status"`
}

func (q *Queries) UpdateTaskStatusByEntity(ctx context.Context, arg UpdateTaskStatusByEntityParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatusByEntity, arg.EntityID, arg.Status)
	return err
}
