// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_templates.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getEmailTemplateBySlug = `-- name: GetEmailTemplateBySlug :one
SELECT id, slug, name, subject, body_html, placeholders, created_at, updated_at FROM email_templates WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetEmailTemplateBySlug(ctx context.Context, slug string) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, getEmailTemplateBySlug, slug)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Subject,
		&i.BodyHtml,
		&i.Placeholders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmailTemplates = `-- name: ListEmailTemplates :many
SELECT id, slug, name, subject, body_html, placeholders, created_at, updated_at FROM email_templates ORDER BY name ASC
`

func (q *Queries) ListEmailTemplates(ctx context.Context) ([]EmailTemplate, error) {
	rows, err := q.db.Query(ctx, listEmailTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailTemplate
	for rows.Next() {
		var i EmailTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Subject,
			&i.BodyHtml,
			&i.Placeholders,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailTemplate = `-- name: UpdateEmailTemplate :one
UPDATE email_templates 
SET subject = $2, body_html = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, slug, name, subject, body_html, placeholders, created_at, updated_at
`

type UpdateEmailTemplateParams struct {
	ID       uuid.UUID `json:"id"`
	Subject  string    `json:"subject"`
	BodyHtml string    `json:"body_html"`
}

func (q *Queries) UpdateEmailTemplate(ctx context.Context, arg UpdateEmailTemplateParams) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, updateEmailTemplate, arg.ID, arg.Subject, arg.BodyHtml)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Subject,
		&i.BodyHtml,
		&i.Placeholders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
