// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hierarchy.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBranches = `-- name: GetBranches :many
SELECT id, company_id, name, location, head_id FROM branches ORDER BY name ASC
`

type GetBranchesRow struct {
	ID        uuid.UUID   `json:"id"`
	CompanyID uuid.UUID   `json:"company_id"`
	Name      string      `json:"name"`
	Location  pgtype.Text `json:"location"`
	HeadID    pgtype.UUID `json:"head_id"`
}

func (q *Queries) GetBranches(ctx context.Context) ([]GetBranchesRow, error) {
	rows, err := q.db.Query(ctx, getBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBranchesRow
	for rows.Next() {
		var i GetBranchesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Location,
			&i.HeadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompanies = `-- name: GetCompanies :many
SELECT id, name, address, created_at FROM companies ORDER BY name ASC
`

type GetCompaniesRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Address   pgtype.Text        `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetCompanies(ctx context.Context) ([]GetCompaniesRow, error) {
	rows, err := q.db.Query(ctx, getCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompaniesRow
	for rows.Next() {
		var i GetCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDepartments = `-- name: GetDepartments :many
SELECT id, branch_id, name, head_id FROM departments ORDER BY name ASC
`

type GetDepartmentsRow struct {
	ID       uuid.UUID   `json:"id"`
	BranchID uuid.UUID   `json:"branch_id"`
	Name     string      `json:"name"`
	HeadID   pgtype.UUID `json:"head_id"`
}

func (q *Queries) GetDepartments(ctx context.Context) ([]GetDepartmentsRow, error) {
	rows, err := q.db.Query(ctx, getDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDepartmentsRow
	for rows.Next() {
		var i GetDepartmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.HeadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersForHierarchy = `-- name: GetUsersForHierarchy :many
SELECT u.id, u.full_name, u.role_id, r.name as role_name, u.department_id
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.status = 'approved' OR u.status = 'active'
ORDER BY u.full_name ASC
`

type GetUsersForHierarchyRow struct {
	ID           uuid.UUID   `json:"id"`
	FullName     string      `json:"full_name"`
	RoleID       int32       `json:"role_id"`
	RoleName     pgtype.Text `json:"role_name"`
	DepartmentID pgtype.UUID `json:"department_id"`
}

func (q *Queries) GetUsersForHierarchy(ctx context.Context) ([]GetUsersForHierarchyRow, error) {
	rows, err := q.db.Query(ctx, getUsersForHierarchy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersForHierarchyRow
	for rows.Next() {
		var i GetUsersForHierarchyRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.RoleID,
			&i.RoleName,
			&i.DepartmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartmentHead = `-- name: UpdateDepartmentHead :exec
UPDATE departments SET head_id = $1 WHERE id = $2
`

type UpdateDepartmentHeadParams struct {
	HeadID pgtype.UUID `json:"head_id"`
	ID     uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateDepartmentHead(ctx context.Context, arg UpdateDepartmentHeadParams) error {
	_, err := q.db.Exec(ctx, updateDepartmentHead, arg.HeadID, arg.ID)
	return err
}

const updateUserDepartment = `-- name: UpdateUserDepartment :exec
UPDATE users SET department_id = $1 WHERE id = $2
`

type UpdateUserDepartmentParams struct {
	DepartmentID pgtype.UUID `json:"department_id"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUserDepartment(ctx context.Context, arg UpdateUserDepartmentParams) error {
	_, err := q.db.Exec(ctx, updateUserDepartment, arg.DepartmentID, arg.ID)
	return err
}
