// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integration_nodes.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIntegrationNode = `-- name: CreateIntegrationNode :one
INSERT INTO integration_nodes (
    name, service_type, driver, endpoint, is_critical, config_json
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, service_type, driver, endpoint, is_active, is_critical, config_json, status, last_latency, latency_history, last_check_at, last_error, created_at, updated_at
`

type CreateIntegrationNodeParams struct {
	Name        string      `json:"name"`
	ServiceType string      `json:"service_type"`
	Driver      pgtype.Text `json:"driver"`
	Endpoint    string      `json:"endpoint"`
	IsCritical  pgtype.Bool `json:"is_critical"`
	ConfigJson  []byte      `json:"config_json"`
}

func (q *Queries) CreateIntegrationNode(ctx context.Context, arg CreateIntegrationNodeParams) (IntegrationNode, error) {
	row := q.db.QueryRow(ctx, createIntegrationNode,
		arg.Name,
		arg.ServiceType,
		arg.Driver,
		arg.Endpoint,
		arg.IsCritical,
		arg.ConfigJson,
	)
	var i IntegrationNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServiceType,
		&i.Driver,
		&i.Endpoint,
		&i.IsActive,
		&i.IsCritical,
		&i.ConfigJson,
		&i.Status,
		&i.LastLatency,
		&i.LatencyHistory,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIntegrationNode = `-- name: DeleteIntegrationNode :exec
DELETE FROM integration_nodes
WHERE id = $1
`

func (q *Queries) DeleteIntegrationNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIntegrationNode, id)
	return err
}

const getIntegrationNode = `-- name: GetIntegrationNode :one
SELECT id, name, service_type, driver, endpoint, is_active, is_critical, config_json, status, last_latency, latency_history, last_check_at, last_error, created_at, updated_at FROM integration_nodes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetIntegrationNode(ctx context.Context, id uuid.UUID) (IntegrationNode, error) {
	row := q.db.QueryRow(ctx, getIntegrationNode, id)
	var i IntegrationNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServiceType,
		&i.Driver,
		&i.Endpoint,
		&i.IsActive,
		&i.IsCritical,
		&i.ConfigJson,
		&i.Status,
		&i.LastLatency,
		&i.LatencyHistory,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationNodeByType = `-- name: GetIntegrationNodeByType :one
SELECT id, name, service_type, driver, endpoint, is_active, is_critical, config_json, status, last_latency, latency_history, last_check_at, last_error, created_at, updated_at FROM integration_nodes
WHERE service_type = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetIntegrationNodeByType(ctx context.Context, serviceType string) (IntegrationNode, error) {
	row := q.db.QueryRow(ctx, getIntegrationNodeByType, serviceType)
	var i IntegrationNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServiceType,
		&i.Driver,
		&i.Endpoint,
		&i.IsActive,
		&i.IsCritical,
		&i.ConfigJson,
		&i.Status,
		&i.LastLatency,
		&i.LatencyHistory,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrationNodes = `-- name: ListIntegrationNodes :many
SELECT id, name, service_type, driver, endpoint, is_active, is_critical, config_json, status, last_latency, latency_history, last_check_at, last_error, created_at, updated_at FROM integration_nodes
ORDER BY service_type, name
`

func (q *Queries) ListIntegrationNodes(ctx context.Context) ([]IntegrationNode, error) {
	rows, err := q.db.Query(ctx, listIntegrationNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationNode
	for rows.Next() {
		var i IntegrationNode
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ServiceType,
			&i.Driver,
			&i.Endpoint,
			&i.IsActive,
			&i.IsCritical,
			&i.ConfigJson,
			&i.Status,
			&i.LastLatency,
			&i.LatencyHistory,
			&i.LastCheckAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntegrationNodeConfig = `-- name: UpdateIntegrationNodeConfig :one
UPDATE integration_nodes
SET 
    name = $2,
    endpoint = $3,
    is_active = $4,
    is_critical = $5,
    config_json = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, service_type, driver, endpoint, is_active, is_critical, config_json, status, last_latency, latency_history, last_check_at, last_error, created_at, updated_at
`

type UpdateIntegrationNodeConfigParams struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	Endpoint   string      `json:"endpoint"`
	IsActive   pgtype.Bool `json:"is_active"`
	IsCritical pgtype.Bool `json:"is_critical"`
	ConfigJson []byte      `json:"config_json"`
}

func (q *Queries) UpdateIntegrationNodeConfig(ctx context.Context, arg UpdateIntegrationNodeConfigParams) (IntegrationNode, error) {
	row := q.db.QueryRow(ctx, updateIntegrationNodeConfig,
		arg.ID,
		arg.Name,
		arg.Endpoint,
		arg.IsActive,
		arg.IsCritical,
		arg.ConfigJson,
	)
	var i IntegrationNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServiceType,
		&i.Driver,
		&i.Endpoint,
		&i.IsActive,
		&i.IsCritical,
		&i.ConfigJson,
		&i.Status,
		&i.LastLatency,
		&i.LatencyHistory,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIntegrationNodeStatus = `-- name: UpdateIntegrationNodeStatus :one
UPDATE integration_nodes
SET 
    status = $2,
    last_latency = $3,
    latency_history = (latency_history || $3::int)[GREATEST(1, array_upper(latency_history || $3::int, 1) - 19) : array_upper(latency_history || $3::int, 1)],
    last_check_at = CURRENT_TIMESTAMP,
    last_error = $4
WHERE id = $1
RETURNING id, name, service_type, driver, endpoint, is_active, is_critical, config_json, status, last_latency, latency_history, last_check_at, last_error, created_at, updated_at
`

type UpdateIntegrationNodeStatusParams struct {
	ID          uuid.UUID   `json:"id"`
	Status      pgtype.Text `json:"status"`
	LastLatency pgtype.Int4 `json:"last_latency"`
	LastError   pgtype.Text `json:"last_error"`
}

func (q *Queries) UpdateIntegrationNodeStatus(ctx context.Context, arg UpdateIntegrationNodeStatusParams) (IntegrationNode, error) {
	row := q.db.QueryRow(ctx, updateIntegrationNodeStatus,
		arg.ID,
		arg.Status,
		arg.LastLatency,
		arg.LastError,
	)
	var i IntegrationNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServiceType,
		&i.Driver,
		&i.Endpoint,
		&i.IsActive,
		&i.IsCritical,
		&i.ConfigJson,
		&i.Status,
		&i.LastLatency,
		&i.LatencyHistory,
		&i.LastCheckAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
