// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loans.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveLoanRequestL1 = `-- name: ApproveLoanRequestL1 :exec
UPDATE loan_requests
SET status = 'l1_approved', l1_approved_by = $2, l1_approved_at = NOW(), 
    borrow_date = NOW(), due_date = NOW() + (duration_days || ' days')::interval,
    updated_at = NOW()
WHERE id = $1
`

type ApproveLoanRequestL1Params struct {
	ID           uuid.UUID   `json:"id"`
	L1ApprovedBy pgtype.UUID `json:"l1_approved_by"`
}

func (q *Queries) ApproveLoanRequestL1(ctx context.Context, arg ApproveLoanRequestL1Params) error {
	_, err := q.db.Exec(ctx, approveLoanRequestL1, arg.ID, arg.L1ApprovedBy)
	return err
}

const countUserLoanRequests = `-- name: CountUserLoanRequests :one
SELECT COUNT(*) FROM loan_requests WHERE user_id = $1
`

func (q *Queries) CountUserLoanRequests(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserLoanRequests, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoanRequest = `-- name: CreateLoanRequest :one
INSERT INTO loan_requests (
    request_no, user_id, purpose, duration_days, notes, status,
    company_id, branch_id, department_id
) VALUES (
    $1, $2, $3, $4, $5, 'pending', $6, $7, $8
) RETURNING id, request_no, user_id, purpose, department_filter, duration_days, notes, approver_notes, status, l1_approved_by, l1_approved_at, l1_rejection_reason, l2_approved_by, l2_approved_at, l2_rejection_reason, borrow_date, due_date, return_date, created_at, updated_at, company_id, branch_id, department_id
`

type CreateLoanRequestParams struct {
	RequestNo    string      `json:"request_no"`
	UserID       uuid.UUID   `json:"user_id"`
	Purpose      string      `json:"purpose"`
	DurationDays int32       `json:"duration_days"`
	Notes        pgtype.Text `json:"notes"`
	CompanyID    pgtype.UUID `json:"company_id"`
	BranchID     pgtype.UUID `json:"branch_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
}

func (q *Queries) CreateLoanRequest(ctx context.Context, arg CreateLoanRequestParams) (LoanRequest, error) {
	row := q.db.QueryRow(ctx, createLoanRequest,
		arg.RequestNo,
		arg.UserID,
		arg.Purpose,
		arg.DurationDays,
		arg.Notes,
		arg.CompanyID,
		arg.BranchID,
		arg.DepartmentID,
	)
	var i LoanRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNo,
		&i.UserID,
		&i.Purpose,
		&i.DepartmentFilter,
		&i.DurationDays,
		&i.Notes,
		&i.ApproverNotes,
		&i.Status,
		&i.L1ApprovedBy,
		&i.L1ApprovedAt,
		&i.L1RejectionReason,
		&i.L2ApprovedBy,
		&i.L2ApprovedAt,
		&i.L2RejectionReason,
		&i.BorrowDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.BranchID,
		&i.DepartmentID,
	)
	return i, err
}

const createLoanRequestItem = `-- name: CreateLoanRequestItem :one
INSERT INTO loan_request_items (
    loan_request_id, document_id, category, sensitivity, method
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, loan_request_id, document_id, category, sensitivity, reason, method, status, picked_up_at, returned_at, created_at
`

type CreateLoanRequestItemParams struct {
	LoanRequestID uuid.UUID   `json:"loan_request_id"`
	DocumentID    uuid.UUID   `json:"document_id"`
	Category      pgtype.Text `json:"category"`
	Sensitivity   pgtype.Text `json:"sensitivity"`
	Method        pgtype.Text `json:"method"`
}

func (q *Queries) CreateLoanRequestItem(ctx context.Context, arg CreateLoanRequestItemParams) (LoanRequestItem, error) {
	row := q.db.QueryRow(ctx, createLoanRequestItem,
		arg.LoanRequestID,
		arg.DocumentID,
		arg.Category,
		arg.Sensitivity,
		arg.Method,
	)
	var i LoanRequestItem
	err := row.Scan(
		&i.ID,
		&i.LoanRequestID,
		&i.DocumentID,
		&i.Category,
		&i.Sensitivity,
		&i.Reason,
		&i.Method,
		&i.Status,
		&i.PickedUpAt,
		&i.ReturnedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLoanRequest = `-- name: GetLoanRequest :one
SELECT 
    lr.id, lr.request_no, lr.user_id, lr.purpose, lr.duration_days, lr.notes, 
    lr.status, lr.borrow_date, lr.due_date, lr.return_date,
    lr.l1_approved_by, lr.l1_approved_at, lr.l2_approved_by, lr.l2_approved_at,
    lr.created_at, lr.updated_at,
    u.full_name as user_name,
    dept.name as department_name,
    (SELECT COUNT(*) FROM loan_request_items WHERE loan_request_id = lr.id) as items_count
FROM loan_requests lr
JOIN users u ON lr.user_id = u.id
LEFT JOIN departments dept ON lr.department_id = dept.id
WHERE lr.id = $1 LIMIT 1
`

type GetLoanRequestRow struct {
	ID             uuid.UUID          `json:"id"`
	RequestNo      string             `json:"request_no"`
	UserID         uuid.UUID          `json:"user_id"`
	Purpose        string             `json:"purpose"`
	DurationDays   int32              `json:"duration_days"`
	Notes          pgtype.Text        `json:"notes"`
	Status         string             `json:"status"`
	BorrowDate     pgtype.Timestamptz `json:"borrow_date"`
	DueDate        pgtype.Timestamptz `json:"due_date"`
	ReturnDate     pgtype.Timestamptz `json:"return_date"`
	L1ApprovedBy   pgtype.UUID        `json:"l1_approved_by"`
	L1ApprovedAt   pgtype.Timestamptz `json:"l1_approved_at"`
	L2ApprovedBy   pgtype.UUID        `json:"l2_approved_by"`
	L2ApprovedAt   pgtype.Timestamptz `json:"l2_approved_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UserName       string             `json:"user_name"`
	DepartmentName pgtype.Text        `json:"department_name"`
	ItemsCount     int64              `json:"items_count"`
}

func (q *Queries) GetLoanRequest(ctx context.Context, id uuid.UUID) (GetLoanRequestRow, error) {
	row := q.db.QueryRow(ctx, getLoanRequest, id)
	var i GetLoanRequestRow
	err := row.Scan(
		&i.ID,
		&i.RequestNo,
		&i.UserID,
		&i.Purpose,
		&i.DurationDays,
		&i.Notes,
		&i.Status,
		&i.BorrowDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.L1ApprovedBy,
		&i.L1ApprovedAt,
		&i.L2ApprovedBy,
		&i.L2ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.DepartmentName,
		&i.ItemsCount,
	)
	return i, err
}

const getLoanRequestItems = `-- name: GetLoanRequestItems :many
SELECT 
    lri.id, lri.loan_request_id, lri.document_id, lri.category, lri.sensitivity,
    lri.method, lri.status, lri.picked_up_at, lri.returned_at, lri.created_at,
    d.title as document_title,
    d.file_name as document_filename
FROM loan_request_items lri
JOIN documents d ON lri.document_id = d.id
WHERE lri.loan_request_id = $1
ORDER BY lri.created_at ASC
`

type GetLoanRequestItemsRow struct {
	ID               uuid.UUID          `json:"id"`
	LoanRequestID    uuid.UUID          `json:"loan_request_id"`
	DocumentID       uuid.UUID          `json:"document_id"`
	Category         pgtype.Text        `json:"category"`
	Sensitivity      pgtype.Text        `json:"sensitivity"`
	Method           pgtype.Text        `json:"method"`
	Status           pgtype.Text        `json:"status"`
	PickedUpAt       pgtype.Timestamptz `json:"picked_up_at"`
	ReturnedAt       pgtype.Timestamptz `json:"returned_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DocumentTitle    string             `json:"document_title"`
	DocumentFilename pgtype.Text        `json:"document_filename"`
}

func (q *Queries) GetLoanRequestItems(ctx context.Context, loanRequestID uuid.UUID) ([]GetLoanRequestItemsRow, error) {
	rows, err := q.db.Query(ctx, getLoanRequestItems, loanRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLoanRequestItemsRow
	for rows.Next() {
		var i GetLoanRequestItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.LoanRequestID,
			&i.DocumentID,
			&i.Category,
			&i.Sensitivity,
			&i.Method,
			&i.Status,
			&i.PickedUpAt,
			&i.ReturnedAt,
			&i.CreatedAt,
			&i.DocumentTitle,
			&i.DocumentFilename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countL1ApprovedLoans = `-- name: CountL1ApprovedLoans :one
SELECT COUNT(*) FROM loan_requests WHERE status = 'l1_approved'
`

func (q *Queries) CountL1ApprovedLoans(ctx context.Context) (int64, error) {
	var count int64
	err := q.db.QueryRow(ctx, countL1ApprovedLoans).Scan(&count)
	return count, err
}

const getNextLoanRequestNo = `-- name: GetNextLoanRequestNo :one
SELECT COALESCE(MAX(CAST(SUBSTRING(request_no FROM 'LOAN-\d{4}-\d{2}-(\d+)') AS INT)), 0) + 1 as next_seq
FROM loan_requests
WHERE request_no LIKE 'LOAN-' || to_char(NOW(), 'YYYY-MM') || '-%'
`

func (q *Queries) GetNextLoanRequestNo(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextLoanRequestNo)
	var next_seq int32
	err := row.Scan(&next_seq)
	return next_seq, err
}

const listAllLoanRequests = `-- name: ListAllLoanRequests :many
SELECT 
    lr.id, lr.request_no, lr.user_id, lr.purpose, lr.duration_days, lr.notes, 
    lr.status, lr.borrow_date, lr.due_date, lr.return_date,
    lr.l1_approved_by, lr.l1_approved_at,
    lr.created_at, lr.updated_at,
    u.full_name as user_name,
    dept.name as department_name,
    (SELECT COUNT(*) FROM loan_request_items WHERE loan_request_id = lr.id) as items_count
FROM loan_requests lr
JOIN users u ON lr.user_id = u.id
LEFT JOIN departments dept ON lr.department_id = dept.id
ORDER BY lr.created_at DESC
LIMIT $1
`

type ListAllLoanRequestsRow struct {
	ID             uuid.UUID          `json:"id"`
	RequestNo      string             `json:"request_no"`
	UserID         uuid.UUID          `json:"user_id"`
	Purpose        string             `json:"purpose"`
	DurationDays   int32              `json:"duration_days"`
	Notes          pgtype.Text        `json:"notes"`
	Status         string             `json:"status"`
	BorrowDate     pgtype.Timestamptz `json:"borrow_date"`
	DueDate        pgtype.Timestamptz `json:"due_date"`
	ReturnDate     pgtype.Timestamptz `json:"return_date"`
	L1ApprovedBy   pgtype.UUID        `json:"l1_approved_by"`
	L1ApprovedAt   pgtype.Timestamptz `json:"l1_approved_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UserName       string             `json:"user_name"`
	DepartmentName pgtype.Text        `json:"department_name"`
	ItemsCount     int64              `json:"items_count"`
}

func (q *Queries) ListAllLoanRequests(ctx context.Context, limit int32) ([]ListAllLoanRequestsRow, error) {
	rows, err := q.db.Query(ctx, listAllLoanRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllLoanRequestsRow
	for rows.Next() {
		var i ListAllLoanRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestNo,
			&i.UserID,
			&i.Purpose,
			&i.DurationDays,
			&i.Notes,
			&i.Status,
			&i.BorrowDate,
			&i.DueDate,
			&i.ReturnDate,
			&i.L1ApprovedBy,
			&i.L1ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.DepartmentName,
			&i.ItemsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLoanRequests = `-- name: ListUserLoanRequests :many
SELECT 
    lr.id, lr.request_no, lr.user_id, lr.purpose, lr.duration_days, lr.notes, 
    lr.status, lr.borrow_date, lr.due_date, lr.return_date,
    lr.l1_approved_by, lr.l1_approved_at,
    lr.created_at, lr.updated_at,
    u.full_name as user_name,
    dept.name as department_name,
    (SELECT COUNT(*) FROM loan_request_items WHERE loan_request_id = lr.id) as items_count
FROM loan_requests lr
JOIN users u ON lr.user_id = u.id
LEFT JOIN departments dept ON lr.department_id = dept.id
WHERE lr.user_id = $1
ORDER BY lr.created_at DESC
`

type ListUserLoanRequestsRow struct {
	ID             uuid.UUID          `json:"id"`
	RequestNo      string             `json:"request_no"`
	UserID         uuid.UUID          `json:"user_id"`
	Purpose        string             `json:"purpose"`
	DurationDays   int32              `json:"duration_days"`
	Notes          pgtype.Text        `json:"notes"`
	Status         string             `json:"status"`
	BorrowDate     pgtype.Timestamptz `json:"borrow_date"`
	DueDate        pgtype.Timestamptz `json:"due_date"`
	ReturnDate     pgtype.Timestamptz `json:"return_date"`
	L1ApprovedBy   pgtype.UUID        `json:"l1_approved_by"`
	L1ApprovedAt   pgtype.Timestamptz `json:"l1_approved_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UserName       string             `json:"user_name"`
	DepartmentName pgtype.Text        `json:"department_name"`
	ItemsCount     int64              `json:"items_count"`
}

func (q *Queries) ListUserLoanRequests(ctx context.Context, userID uuid.UUID) ([]ListUserLoanRequestsRow, error) {
	rows, err := q.db.Query(ctx, listUserLoanRequests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserLoanRequestsRow
	for rows.Next() {
		var i ListUserLoanRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestNo,
			&i.UserID,
			&i.Purpose,
			&i.DurationDays,
			&i.Notes,
			&i.Status,
			&i.BorrowDate,
			&i.DueDate,
			&i.ReturnDate,
			&i.L1ApprovedBy,
			&i.L1ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.DepartmentName,
			&i.ItemsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectLoanRequest = `-- name: RejectLoanRequest :exec
UPDATE loan_requests
SET status = 'rejected', l1_approved_by = $2, l1_rejection_reason = $3, updated_at = NOW()
WHERE id = $1
`

type RejectLoanRequestParams struct {
	ID                uuid.UUID   `json:"id"`
	L1ApprovedBy      pgtype.UUID `json:"l1_approved_by"`
	L1RejectionReason pgtype.Text `json:"l1_rejection_reason"`
}

func (q *Queries) RejectLoanRequest(ctx context.Context, arg RejectLoanRequestParams) error {
	_, err := q.db.Exec(ctx, rejectLoanRequest, arg.ID, arg.L1ApprovedBy, arg.L1RejectionReason)
	return err
}

const updateLoanRequestStatus = `-- name: UpdateLoanRequestStatus :exec
UPDATE loan_requests 
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateLoanRequestStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateLoanRequestStatus(ctx context.Context, arg UpdateLoanRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateLoanRequestStatus, arg.ID, arg.Status)
	return err
}
