// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loans.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveLoanRequestL1 = `-- name: ApproveLoanRequestL1 :exec
UPDATE loan_requests
SET status = 'l1_approved', l1_approved_by = $2, l1_approved_at = NOW(), 
    borrow_date = NOW(), due_date = NOW() + (duration_days || ' days')::interval,
    updated_at = NOW()
WHERE id = $1
`

type ApproveLoanRequestL1Params struct {
	ID           uuid.UUID   `json:"id"`
	L1ApprovedBy pgtype.UUID `json:"l1_approved_by"`
}

func (q *Queries) ApproveLoanRequestL1(ctx context.Context, arg ApproveLoanRequestL1Params) error {
	_, err := q.db.Exec(ctx, approveLoanRequestL1, arg.ID, arg.L1ApprovedBy)
	return err
}

const countL1ApprovedLoans = `-- name: CountL1ApprovedLoans :one
SELECT COUNT(*) FROM loan_requests WHERE status = 'l1_approved'
`

func (q *Queries) CountL1ApprovedLoans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countL1ApprovedLoans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserLoanRequests = `-- name: CountUserLoanRequests :one
SELECT COUNT(*) FROM loan_requests WHERE user_id = $1
`

func (q *Queries) CountUserLoanRequests(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserLoanRequests, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoanExtension = `-- name: CreateLoanExtension :one
INSERT INTO loan_extensions (
    loan_request_id, requested_by, extension_days, reason, status
) VALUES (
    $1, $2, $3, $4, 'pending'
) RETURNING id, loan_request_id, requested_by, extension_days, reason, status, approved_by, decided_at, created_at
`

type CreateLoanExtensionParams struct {
	LoanRequestID uuid.UUID `json:"loan_request_id"`
	RequestedBy   uuid.UUID `json:"requested_by"`
	ExtensionDays int32     `json:"extension_days"`
	Reason        string    `json:"reason"`
}

func (q *Queries) CreateLoanExtension(ctx context.Context, arg CreateLoanExtensionParams) (LoanExtension, error) {
	row := q.db.QueryRow(ctx, createLoanExtension,
		arg.LoanRequestID,
		arg.RequestedBy,
		arg.ExtensionDays,
		arg.Reason,
	)
	var i LoanExtension
	err := row.Scan(
		&i.ID,
		&i.LoanRequestID,
		&i.RequestedBy,
		&i.ExtensionDays,
		&i.Reason,
		&i.Status,
		&i.ApprovedBy,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createLoanRequest = `-- name: CreateLoanRequest :one
INSERT INTO loan_requests (
    request_no, user_id, purpose, duration_days, notes, status,
    company_id, branch_id, department_id
) VALUES (
    $1, $2, $3, $4, $5, 'pending', $6, $7, $8
) RETURNING id, request_no, user_id, purpose, department_filter, duration_days, notes, approver_notes, status, l1_approved_by, l1_approved_at, l1_rejection_reason, l2_approved_by, l2_approved_at, l2_rejection_reason, borrow_date, due_date, return_date, created_at, updated_at, company_id, branch_id, department_id
`

type CreateLoanRequestParams struct {
	RequestNo    string      `json:"request_no"`
	UserID       uuid.UUID   `json:"user_id"`
	Purpose      string      `json:"purpose"`
	DurationDays int32       `json:"duration_days"`
	Notes        pgtype.Text `json:"notes"`
	CompanyID    pgtype.UUID `json:"company_id"`
	BranchID     pgtype.UUID `json:"branch_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
}

func (q *Queries) CreateLoanRequest(ctx context.Context, arg CreateLoanRequestParams) (LoanRequest, error) {
	row := q.db.QueryRow(ctx, createLoanRequest,
		arg.RequestNo,
		arg.UserID,
		arg.Purpose,
		arg.DurationDays,
		arg.Notes,
		arg.CompanyID,
		arg.BranchID,
		arg.DepartmentID,
	)
	var i LoanRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNo,
		&i.UserID,
		&i.Purpose,
		&i.DepartmentFilter,
		&i.DurationDays,
		&i.Notes,
		&i.ApproverNotes,
		&i.Status,
		&i.L1ApprovedBy,
		&i.L1ApprovedAt,
		&i.L1RejectionReason,
		&i.L2ApprovedBy,
		&i.L2ApprovedAt,
		&i.L2RejectionReason,
		&i.BorrowDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.BranchID,
		&i.DepartmentID,
	)
	return i, err
}

const createLoanRequestItem = `-- name: CreateLoanRequestItem :one
INSERT INTO loan_request_items (
    loan_request_id, document_id, category, sensitivity, method
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, loan_request_id, document_id, category, sensitivity, reason, method, status, picked_up_at, returned_at, created_at
`

type CreateLoanRequestItemParams struct {
	LoanRequestID uuid.UUID   `json:"loan_request_id"`
	DocumentID    uuid.UUID   `json:"document_id"`
	Category      pgtype.Text `json:"category"`
	Sensitivity   pgtype.Text `json:"sensitivity"`
	Method        pgtype.Text `json:"method"`
}

func (q *Queries) CreateLoanRequestItem(ctx context.Context, arg CreateLoanRequestItemParams) (LoanRequestItem, error) {
	row := q.db.QueryRow(ctx, createLoanRequestItem,
		arg.LoanRequestID,
		arg.DocumentID,
		arg.Category,
		arg.Sensitivity,
		arg.Method,
	)
	var i LoanRequestItem
	err := row.Scan(
		&i.ID,
		&i.LoanRequestID,
		&i.DocumentID,
		&i.Category,
		&i.Sensitivity,
		&i.Reason,
		&i.Method,
		&i.Status,
		&i.PickedUpAt,
		&i.ReturnedAt,
		&i.CreatedAt,
	)
	return i, err
}

const extendLoanRequestDueDate = `-- name: ExtendLoanRequestDueDate :exec
UPDATE loan_requests
SET due_date = due_date + ($2::int * interval '1 day'), 
    status = 'active', 
    updated_at = NOW()
WHERE id = $1
`

type ExtendLoanRequestDueDateParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 int32     `json:"column_2"`
}

func (q *Queries) ExtendLoanRequestDueDate(ctx context.Context, arg ExtendLoanRequestDueDateParams) error {
	_, err := q.db.Exec(ctx, extendLoanRequestDueDate, arg.ID, arg.Column2)
	return err
}

const getLoanExtension = `-- name: GetLoanExtension :one
SELECT 
    le.id, le.loan_request_id, le.requested_by, le.extension_days, le.reason, 
    le.status, le.approved_by, le.decided_at, le.created_at,
    u.full_name as requested_by_name,
    lr.request_no, lr.due_date as current_due_date
FROM loan_extensions le
JOIN users u ON le.requested_by = u.id
JOIN loan_requests lr ON le.loan_request_id = lr.id
WHERE le.id = $1 LIMIT 1
`

type GetLoanExtensionRow struct {
	ID              uuid.UUID          `json:"id"`
	LoanRequestID   uuid.UUID          `json:"loan_request_id"`
	RequestedBy     uuid.UUID          `json:"requested_by"`
	ExtensionDays   int32              `json:"extension_days"`
	Reason          string             `json:"reason"`
	Status          pgtype.Text        `json:"status"`
	ApprovedBy      pgtype.UUID        `json:"approved_by"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	RequestedByName string             `json:"requested_by_name"`
	RequestNo       string             `json:"request_no"`
	CurrentDueDate  pgtype.Timestamptz `json:"current_due_date"`
}

func (q *Queries) GetLoanExtension(ctx context.Context, id uuid.UUID) (GetLoanExtensionRow, error) {
	row := q.db.QueryRow(ctx, getLoanExtension, id)
	var i GetLoanExtensionRow
	err := row.Scan(
		&i.ID,
		&i.LoanRequestID,
		&i.RequestedBy,
		&i.ExtensionDays,
		&i.Reason,
		&i.Status,
		&i.ApprovedBy,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.RequestedByName,
		&i.RequestNo,
		&i.CurrentDueDate,
	)
	return i, err
}

const getLoanRequest = `-- name: GetLoanRequest :one
SELECT 
    lr.id, lr.request_no, lr.user_id, lr.purpose, lr.duration_days, lr.notes, 
    lr.status, lr.borrow_date, lr.due_date, lr.return_date,
    lr.l1_approved_by, lr.l1_approved_at, lr.l1_rejection_reason, 
    lr.l2_approved_by, lr.l2_approved_at, lr.l2_rejection_reason,
    lr.created_at, lr.updated_at,
    u.full_name as user_name,
    dept.name as department_name,
    (SELECT COUNT(*) FROM loan_request_items WHERE loan_request_id = lr.id) as items_count
FROM loan_requests lr
JOIN users u ON lr.user_id = u.id
LEFT JOIN departments dept ON lr.department_id = dept.id
WHERE lr.id = $1 LIMIT 1
`

type GetLoanRequestRow struct {
	ID                uuid.UUID          `json:"id"`
	RequestNo         string             `json:"request_no"`
	UserID            uuid.UUID          `json:"user_id"`
	Purpose           string             `json:"purpose"`
	DurationDays      int32              `json:"duration_days"`
	Notes             pgtype.Text        `json:"notes"`
	Status            string             `json:"status"`
	BorrowDate        pgtype.Timestamptz `json:"borrow_date"`
	DueDate           pgtype.Timestamptz `json:"due_date"`
	ReturnDate        pgtype.Timestamptz `json:"return_date"`
	L1ApprovedBy      pgtype.UUID        `json:"l1_approved_by"`
	L1ApprovedAt      pgtype.Timestamptz `json:"l1_approved_at"`
	L1RejectionReason pgtype.Text        `json:"l1_rejection_reason"`
	L2ApprovedBy      pgtype.UUID        `json:"l2_approved_by"`
	L2ApprovedAt      pgtype.Timestamptz `json:"l2_approved_at"`
	L2RejectionReason pgtype.Text        `json:"l2_rejection_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UserName          string             `json:"user_name"`
	DepartmentName    pgtype.Text        `json:"department_name"`
	ItemsCount        int64              `json:"items_count"`
}

func (q *Queries) GetLoanRequest(ctx context.Context, id uuid.UUID) (GetLoanRequestRow, error) {
	row := q.db.QueryRow(ctx, getLoanRequest, id)
	var i GetLoanRequestRow
	err := row.Scan(
		&i.ID,
		&i.RequestNo,
		&i.UserID,
		&i.Purpose,
		&i.DurationDays,
		&i.Notes,
		&i.Status,
		&i.BorrowDate,
		&i.DueDate,
		&i.ReturnDate,
		&i.L1ApprovedBy,
		&i.L1ApprovedAt,
		&i.L1RejectionReason,
		&i.L2ApprovedBy,
		&i.L2ApprovedAt,
		&i.L2RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.DepartmentName,
		&i.ItemsCount,
	)
	return i, err
}

const getLoanRequestItems = `-- name: GetLoanRequestItems :many
SELECT 
    lri.id, lri.loan_request_id, lri.document_id, lri.category, lri.sensitivity,
    lri.method, lri.status, lri.picked_up_at, lri.returned_at, lri.created_at,
    d.title as document_title,
    d.file_name as document_filename
FROM loan_request_items lri
JOIN documents d ON lri.document_id = d.id
WHERE lri.loan_request_id = $1
ORDER BY lri.created_at ASC
`

type GetLoanRequestItemsRow struct {
	ID               uuid.UUID          `json:"id"`
	LoanRequestID    uuid.UUID          `json:"loan_request_id"`
	DocumentID       uuid.UUID          `json:"document_id"`
	Category         pgtype.Text        `json:"category"`
	Sensitivity      pgtype.Text        `json:"sensitivity"`
	Method           pgtype.Text        `json:"method"`
	Status           pgtype.Text        `json:"status"`
	PickedUpAt       pgtype.Timestamptz `json:"picked_up_at"`
	ReturnedAt       pgtype.Timestamptz `json:"returned_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DocumentTitle    string             `json:"document_title"`
	DocumentFilename pgtype.Text        `json:"document_filename"`
}

func (q *Queries) GetLoanRequestItems(ctx context.Context, loanRequestID uuid.UUID) ([]GetLoanRequestItemsRow, error) {
	rows, err := q.db.Query(ctx, getLoanRequestItems, loanRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLoanRequestItemsRow
	for rows.Next() {
		var i GetLoanRequestItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.LoanRequestID,
			&i.DocumentID,
			&i.Category,
			&i.Sensitivity,
			&i.Method,
			&i.Status,
			&i.PickedUpAt,
			&i.ReturnedAt,
			&i.CreatedAt,
			&i.DocumentTitle,
			&i.DocumentFilename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextLoanRequestNo = `-- name: GetNextLoanRequestNo :one
SELECT COALESCE(MAX(CAST(SUBSTRING(request_no FROM 'LOAN-\d{4}-\d{2}-(\d+)') AS INT)), 0) + 1 as next_seq
FROM loan_requests
WHERE request_no LIKE 'LOAN-' || to_char(NOW(), 'YYYY-MM') || '-%'
`

func (q *Queries) GetNextLoanRequestNo(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextLoanRequestNo)
	var next_seq int32
	err := row.Scan(&next_seq)
	return next_seq, err
}

const getPendingLoanExtensionByLoanRequest = `-- name: GetPendingLoanExtensionByLoanRequest :one
SELECT id, loan_request_id, requested_by, extension_days, reason, status, approved_by, decided_at, created_at 
FROM loan_extensions
WHERE loan_request_id = $1 AND status = 'pending'
LIMIT 1
`

func (q *Queries) GetPendingLoanExtensionByLoanRequest(ctx context.Context, loanRequestID uuid.UUID) (LoanExtension, error) {
	row := q.db.QueryRow(ctx, getPendingLoanExtensionByLoanRequest, loanRequestID)
	var i LoanExtension
	err := row.Scan(
		&i.ID,
		&i.LoanRequestID,
		&i.RequestedBy,
		&i.ExtensionDays,
		&i.Reason,
		&i.Status,
		&i.ApprovedBy,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAllLoanRequests = `-- name: ListAllLoanRequests :many
SELECT 
    lr.id, lr.request_no, lr.user_id, lr.purpose, lr.duration_days, lr.notes, 
    lr.status, lr.borrow_date, lr.due_date, lr.return_date,
    lr.l1_approved_by, lr.l1_approved_at, lr.l1_rejection_reason,
    lr.l2_approved_by, lr.l2_approved_at, lr.l2_rejection_reason,
    lr.created_at, lr.updated_at,
    u.full_name as user_name,
    dept.name as department_name,
    (SELECT COUNT(*) FROM loan_request_items WHERE loan_request_id = lr.id) as items_count
FROM loan_requests lr
JOIN users u ON lr.user_id = u.id
LEFT JOIN departments dept ON lr.department_id = dept.id
ORDER BY lr.created_at DESC
LIMIT $1
`

type ListAllLoanRequestsRow struct {
	ID                uuid.UUID          `json:"id"`
	RequestNo         string             `json:"request_no"`
	UserID            uuid.UUID          `json:"user_id"`
	Purpose           string             `json:"purpose"`
	DurationDays      int32              `json:"duration_days"`
	Notes             pgtype.Text        `json:"notes"`
	Status            string             `json:"status"`
	BorrowDate        pgtype.Timestamptz `json:"borrow_date"`
	DueDate           pgtype.Timestamptz `json:"due_date"`
	ReturnDate        pgtype.Timestamptz `json:"return_date"`
	L1ApprovedBy      pgtype.UUID        `json:"l1_approved_by"`
	L1ApprovedAt      pgtype.Timestamptz `json:"l1_approved_at"`
	L1RejectionReason pgtype.Text        `json:"l1_rejection_reason"`
	L2ApprovedBy      pgtype.UUID        `json:"l2_approved_by"`
	L2ApprovedAt      pgtype.Timestamptz `json:"l2_approved_at"`
	L2RejectionReason pgtype.Text        `json:"l2_rejection_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UserName          string             `json:"user_name"`
	DepartmentName    pgtype.Text        `json:"department_name"`
	ItemsCount        int64              `json:"items_count"`
}

func (q *Queries) ListAllLoanRequests(ctx context.Context, limit int32) ([]ListAllLoanRequestsRow, error) {
	rows, err := q.db.Query(ctx, listAllLoanRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllLoanRequestsRow
	for rows.Next() {
		var i ListAllLoanRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestNo,
			&i.UserID,
			&i.Purpose,
			&i.DurationDays,
			&i.Notes,
			&i.Status,
			&i.BorrowDate,
			&i.DueDate,
			&i.ReturnDate,
			&i.L1ApprovedBy,
			&i.L1ApprovedAt,
			&i.L1RejectionReason,
			&i.L2ApprovedBy,
			&i.L2ApprovedAt,
			&i.L2RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.DepartmentName,
			&i.ItemsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingLoanExtensionsForApprover = `-- name: ListPendingLoanExtensionsForApprover :many
SELECT 
    le.id as extension_id,
    le.loan_request_id,
    le.extension_days,
    le.reason,
    le.status as extension_status,
    le.created_at as extension_created_at,
    lr.request_no,
    lr.due_date as current_due_date,
    u.full_name as requestor_name,
    u.avatar_url as requestor_avatar,
    aw.id as task_id,
    aw.level as approval_level
FROM loan_extensions le
JOIN loan_requests lr ON le.loan_request_id = lr.id
JOIN users u ON le.requested_by = u.id
JOIN approval_workflows aw ON aw.entity_id = le.id AND aw.entity_type = 'loan_extension'
WHERE aw.approver_id = $1 AND aw.status = 'pending'
ORDER BY le.created_at DESC
`

type ListPendingLoanExtensionsForApproverRow struct {
	ExtensionID        uuid.UUID          `json:"extension_id"`
	LoanRequestID      uuid.UUID          `json:"loan_request_id"`
	ExtensionDays      int32              `json:"extension_days"`
	Reason             string             `json:"reason"`
	ExtensionStatus    pgtype.Text        `json:"extension_status"`
	ExtensionCreatedAt pgtype.Timestamptz `json:"extension_created_at"`
	RequestNo          string             `json:"request_no"`
	CurrentDueDate     pgtype.Timestamptz `json:"current_due_date"`
	RequestorName      string             `json:"requestor_name"`
	RequestorAvatar    pgtype.Text        `json:"requestor_avatar"`
	TaskID             uuid.UUID          `json:"task_id"`
	ApprovalLevel      int32              `json:"approval_level"`
}

func (q *Queries) ListPendingLoanExtensionsForApprover(ctx context.Context, approverID uuid.UUID) ([]ListPendingLoanExtensionsForApproverRow, error) {
	rows, err := q.db.Query(ctx, listPendingLoanExtensionsForApprover, approverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingLoanExtensionsForApproverRow
	for rows.Next() {
		var i ListPendingLoanExtensionsForApproverRow
		if err := rows.Scan(
			&i.ExtensionID,
			&i.LoanRequestID,
			&i.ExtensionDays,
			&i.Reason,
			&i.ExtensionStatus,
			&i.ExtensionCreatedAt,
			&i.RequestNo,
			&i.CurrentDueDate,
			&i.RequestorName,
			&i.RequestorAvatar,
			&i.TaskID,
			&i.ApprovalLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLoanRequests = `-- name: ListUserLoanRequests :many
SELECT 
    lr.id, lr.request_no, lr.user_id, lr.purpose, lr.duration_days, lr.notes, 
    lr.status, lr.borrow_date, lr.due_date, lr.return_date,
    lr.l1_approved_by, lr.l1_approved_at, lr.l1_rejection_reason,
    lr.l2_approved_by, lr.l2_approved_at, lr.l2_rejection_reason,
    lr.created_at, lr.updated_at,
    u.full_name as user_name,
    dept.name as department_name,
    (SELECT COUNT(*) FROM loan_request_items WHERE loan_request_id = lr.id) as items_count
FROM loan_requests lr
JOIN users u ON lr.user_id = u.id
LEFT JOIN departments dept ON lr.department_id = dept.id
WHERE lr.user_id = $1
ORDER BY lr.created_at DESC
`

type ListUserLoanRequestsRow struct {
	ID                uuid.UUID          `json:"id"`
	RequestNo         string             `json:"request_no"`
	UserID            uuid.UUID          `json:"user_id"`
	Purpose           string             `json:"purpose"`
	DurationDays      int32              `json:"duration_days"`
	Notes             pgtype.Text        `json:"notes"`
	Status            string             `json:"status"`
	BorrowDate        pgtype.Timestamptz `json:"borrow_date"`
	DueDate           pgtype.Timestamptz `json:"due_date"`
	ReturnDate        pgtype.Timestamptz `json:"return_date"`
	L1ApprovedBy      pgtype.UUID        `json:"l1_approved_by"`
	L1ApprovedAt      pgtype.Timestamptz `json:"l1_approved_at"`
	L1RejectionReason pgtype.Text        `json:"l1_rejection_reason"`
	L2ApprovedBy      pgtype.UUID        `json:"l2_approved_by"`
	L2ApprovedAt      pgtype.Timestamptz `json:"l2_approved_at"`
	L2RejectionReason pgtype.Text        `json:"l2_rejection_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UserName          string             `json:"user_name"`
	DepartmentName    pgtype.Text        `json:"department_name"`
	ItemsCount        int64              `json:"items_count"`
}

func (q *Queries) ListUserLoanRequests(ctx context.Context, userID uuid.UUID) ([]ListUserLoanRequestsRow, error) {
	rows, err := q.db.Query(ctx, listUserLoanRequests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserLoanRequestsRow
	for rows.Next() {
		var i ListUserLoanRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestNo,
			&i.UserID,
			&i.Purpose,
			&i.DurationDays,
			&i.Notes,
			&i.Status,
			&i.BorrowDate,
			&i.DueDate,
			&i.ReturnDate,
			&i.L1ApprovedBy,
			&i.L1ApprovedAt,
			&i.L1RejectionReason,
			&i.L2ApprovedBy,
			&i.L2ApprovedAt,
			&i.L2RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.DepartmentName,
			&i.ItemsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectLoanRequest = `-- name: RejectLoanRequest :exec
UPDATE loan_requests
SET status = 'rejected', l1_approved_by = $2, l1_rejection_reason = $3, updated_at = NOW()
WHERE id = $1
`

type RejectLoanRequestParams struct {
	ID                uuid.UUID   `json:"id"`
	L1ApprovedBy      pgtype.UUID `json:"l1_approved_by"`
	L1RejectionReason pgtype.Text `json:"l1_rejection_reason"`
}

func (q *Queries) RejectLoanRequest(ctx context.Context, arg RejectLoanRequestParams) error {
	_, err := q.db.Exec(ctx, rejectLoanRequest, arg.ID, arg.L1ApprovedBy, arg.L1RejectionReason)
	return err
}

const rejectLoanRequestL2 = `-- name: RejectLoanRequestL2 :exec
UPDATE loan_requests
SET status = 'returned', l2_approved_by = $2, l2_rejection_reason = $3, updated_at = NOW()
WHERE id = $1
`

type RejectLoanRequestL2Params struct {
	ID                uuid.UUID   `json:"id"`
	L2ApprovedBy      pgtype.UUID `json:"l2_approved_by"`
	L2RejectionReason pgtype.Text `json:"l2_rejection_reason"`
}

func (q *Queries) RejectLoanRequestL2(ctx context.Context, arg RejectLoanRequestL2Params) error {
	_, err := q.db.Exec(ctx, rejectLoanRequestL2, arg.ID, arg.L2ApprovedBy, arg.L2RejectionReason)
	return err
}

const updateLoanExtensionStatus = `-- name: UpdateLoanExtensionStatus :exec
UPDATE loan_extensions
SET status = $2, approved_by = $3, decided_at = NOW()
WHERE id = $1
`

type UpdateLoanExtensionStatusParams struct {
	ID         uuid.UUID   `json:"id"`
	Status     pgtype.Text `json:"status"`
	ApprovedBy pgtype.UUID `json:"approved_by"`
}

func (q *Queries) UpdateLoanExtensionStatus(ctx context.Context, arg UpdateLoanExtensionStatusParams) error {
	_, err := q.db.Exec(ctx, updateLoanExtensionStatus, arg.ID, arg.Status, arg.ApprovedBy)
	return err
}

const updateLoanRequestStatus = `-- name: UpdateLoanRequestStatus :exec
UPDATE loan_requests 
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateLoanRequestStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateLoanRequestStatus(ctx context.Context, arg UpdateLoanRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateLoanRequestStatus, arg.ID, arg.Status)
	return err
}
