// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: master.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBox = `-- name: CreateBox :one
INSERT INTO boxes (rack_id, name)
VALUES ($1, $2)
RETURNING id, rack_id, name, created_at
`

type CreateBoxParams struct {
	RackID uuid.UUID `json:"rack_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateBox(ctx context.Context, arg CreateBoxParams) (Box, error) {
	row := q.db.QueryRow(ctx, createBox, arg.RackID, arg.Name)
	var i Box
	err := row.Scan(
		&i.ID,
		&i.RackID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (company_id, name, location, head_id)
VALUES ($1, $2, $3, $4)
RETURNING id, company_id, name, location, head_id, created_at
`

type CreateBranchParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	Name      string      `json:"name"`
	Location  pgtype.Text `json:"location"`
	HeadID    pgtype.UUID `json:"head_id"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.CompanyID,
		arg.Name,
		arg.Location,
		arg.HeadID,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Location,
		&i.HeadID,
		&i.CreatedAt,
	)
	return i, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (name, entity_id, npwp_status, location, status, address)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, address, created_at, entity_id, npwp_status, location, status
`

type CreateCompanyParams struct {
	Name       string      `json:"name"`
	EntityID   pgtype.Text `json:"entity_id"`
	NpwpStatus pgtype.Text `json:"npwp_status"`
	Location   pgtype.Text `json:"location"`
	Status     pgtype.Text `json:"status"`
	Address    pgtype.Text `json:"address"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.Name,
		arg.EntityID,
		arg.NpwpStatus,
		arg.Location,
		arg.Status,
		arg.Address,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.EntityID,
		&i.NpwpStatus,
		&i.Location,
		&i.Status,
	)
	return i, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (branch_id, name, head_id)
VALUES ($1, $2, $3)
RETURNING id, branch_id, name, head_id, created_at
`

type CreateDepartmentParams struct {
	BranchID uuid.UUID   `json:"branch_id"`
	Name     string      `json:"name"`
	HeadID   pgtype.UUID `json:"head_id"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment, arg.BranchID, arg.Name, arg.HeadID)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.HeadID,
		&i.CreatedAt,
	)
	return i, err
}

const createOrdner = `-- name: CreateOrdner :one
INSERT INTO ordners (box_id, name)
VALUES ($1, $2)
RETURNING id, box_id, name, created_at
`

type CreateOrdnerParams struct {
	BoxID uuid.UUID `json:"box_id"`
	Name  string    `json:"name"`
}

func (q *Queries) CreateOrdner(ctx context.Context, arg CreateOrdnerParams) (Ordner, error) {
	row := q.db.QueryRow(ctx, createOrdner, arg.BoxID, arg.Name)
	var i Ordner
	err := row.Scan(
		&i.ID,
		&i.BoxID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createRack = `-- name: CreateRack :one
INSERT INTO racks (department_id, name, location_detail)
VALUES ($1, $2, $3)
RETURNING id, department_id, name, location_detail, created_at
`

type CreateRackParams struct {
	DepartmentID   uuid.UUID   `json:"department_id"`
	Name           string      `json:"name"`
	LocationDetail pgtype.Text `json:"location_detail"`
}

func (q *Queries) CreateRack(ctx context.Context, arg CreateRackParams) (Rack, error) {
	row := q.db.QueryRow(ctx, createRack, arg.DepartmentID, arg.Name, arg.LocationDetail)
	var i Rack
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Name,
		&i.LocationDetail,
		&i.CreatedAt,
	)
	return i, err
}

const createRetentionPolicy = `-- name: CreateRetentionPolicy :one
INSERT INTO retention_policies (name, description, retention_years, department_id, document_category)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, retention_years, department_id, document_category, is_active, created_at, updated_at
`

type CreateRetentionPolicyParams struct {
	Name             string      `json:"name"`
	Description      pgtype.Text `json:"description"`
	RetentionYears   int32       `json:"retention_years"`
	DepartmentID     pgtype.UUID `json:"department_id"`
	DocumentCategory pgtype.Text `json:"document_category"`
}

func (q *Queries) CreateRetentionPolicy(ctx context.Context, arg CreateRetentionPolicyParams) (RetentionPolicy, error) {
	row := q.db.QueryRow(ctx, createRetentionPolicy,
		arg.Name,
		arg.Description,
		arg.RetentionYears,
		arg.DepartmentID,
		arg.DocumentCategory,
	)
	var i RetentionPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RetentionYears,
		&i.DepartmentID,
		&i.DocumentCategory,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRfidTag = `-- name: CreateRfidTag :one
INSERT INTO rfid_tags (tag_id, document_id, status)
VALUES ($1, $2, $3)
RETURNING tag_id, document_id, status, assigned_at
`

type CreateRfidTagParams struct {
	TagID      string    `json:"tag_id"`
	DocumentID uuid.UUID `json:"document_id"`
	Status     string    `json:"status"`
}

func (q *Queries) CreateRfidTag(ctx context.Context, arg CreateRfidTagParams) (RfidTag, error) {
	row := q.db.QueryRow(ctx, createRfidTag, arg.TagID, arg.DocumentID, arg.Status)
	var i RfidTag
	err := row.Scan(
		&i.TagID,
		&i.DocumentID,
		&i.Status,
		&i.AssignedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, description)
VALUES ($1, $2)
RETURNING id, name, description, ldap_group
`

type CreateRoleParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LdapGroup,
	)
	return i, err
}

const deleteBox = `-- name: DeleteBox :exec
DELETE FROM boxes WHERE id = $1
`

func (q *Queries) DeleteBox(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBox, id)
	return err
}

const deleteBranch = `-- name: DeleteBranch :exec
DELETE FROM branches WHERE id = $1
`

func (q *Queries) DeleteBranch(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBranch, id)
	return err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM companies WHERE id = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompany, id)
	return err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepartment, id)
	return err
}

const deleteOrdner = `-- name: DeleteOrdner :exec
DELETE FROM ordners WHERE id = $1
`

func (q *Queries) DeleteOrdner(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrdner, id)
	return err
}

const deleteRack = `-- name: DeleteRack :exec
DELETE FROM racks WHERE id = $1
`

func (q *Queries) DeleteRack(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRack, id)
	return err
}

const deleteRetentionPolicy = `-- name: DeleteRetentionPolicy :exec
DELETE FROM retention_policies WHERE id = $1
`

func (q *Queries) DeleteRetentionPolicy(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRetentionPolicy, id)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const getBox = `-- name: GetBox :one
SELECT id, rack_id, name, created_at FROM boxes WHERE id = $1
`

func (q *Queries) GetBox(ctx context.Context, id uuid.UUID) (Box, error) {
	row := q.db.QueryRow(ctx, getBox, id)
	var i Box
	err := row.Scan(
		&i.ID,
		&i.RackID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getBranch = `-- name: GetBranch :one
SELECT id, company_id, name, location, head_id, created_at FROM branches WHERE id = $1
`

func (q *Queries) GetBranch(ctx context.Context, id uuid.UUID) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranch, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Location,
		&i.HeadID,
		&i.CreatedAt,
	)
	return i, err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, address, created_at, entity_id, npwp_status, location, status FROM companies WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.EntityID,
		&i.NpwpStatus,
		&i.Location,
		&i.Status,
	)
	return i, err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, branch_id, name, head_id, created_at FROM departments WHERE id = $1
`

func (q *Queries) GetDepartment(ctx context.Context, id uuid.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartment, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.HeadID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrdner = `-- name: GetOrdner :one
SELECT id, box_id, name, created_at FROM ordners WHERE id = $1
`

func (q *Queries) GetOrdner(ctx context.Context, id uuid.UUID) (Ordner, error) {
	row := q.db.QueryRow(ctx, getOrdner, id)
	var i Ordner
	err := row.Scan(
		&i.ID,
		&i.BoxID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getRack = `-- name: GetRack :one
SELECT id, department_id, name, location_detail, created_at FROM racks WHERE id = $1
`

func (q *Queries) GetRack(ctx context.Context, id uuid.UUID) (Rack, error) {
	row := q.db.QueryRow(ctx, getRack, id)
	var i Rack
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Name,
		&i.LocationDetail,
		&i.CreatedAt,
	)
	return i, err
}

const getRfidTag = `-- name: GetRfidTag :one
SELECT tag_id, document_id, status, assigned_at FROM rfid_tags WHERE tag_id = $1
`

func (q *Queries) GetRfidTag(ctx context.Context, tagID string) (RfidTag, error) {
	row := q.db.QueryRow(ctx, getRfidTag, tagID)
	var i RfidTag
	err := row.Scan(
		&i.TagID,
		&i.DocumentID,
		&i.Status,
		&i.AssignedAt,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, name, description, ldap_group FROM roles WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id int32) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LdapGroup,
	)
	return i, err
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT id, category, key, value, value_type, description, updated_by, updated_at FROM system_settings WHERE category = $1 AND key = $2
`

type GetSystemSettingParams struct {
	Category string `json:"category"`
	Key      string `json:"key"`
}

func (q *Queries) GetSystemSetting(ctx context.Context, arg GetSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, arg.Category, arg.Key)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Key,
		&i.Value,
		&i.ValueType,
		&i.Description,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemSettingsByCategory = `-- name: GetSystemSettingsByCategory :many
SELECT id, category, key, value, value_type, description, updated_by, updated_at FROM system_settings WHERE category = $1
`

// System Settings
func (q *Queries) GetSystemSettingsByCategory(ctx context.Context, category string) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, getSystemSettingsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemSetting
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Key,
			&i.Value,
			&i.ValueType,
			&i.Description,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarehouseTopology = `-- name: GetWarehouseTopology :many
SELECT 
    c.name as company_name, b.name as branch_name, d.name as department_name,
    r.id as rack_id, r.name as rack_name,
    bx.id as box_id, bx.name as box_name,
    o.id as ordner_id, o.name as ordner_name
FROM companies c
JOIN branches b ON b.company_id = c.id
JOIN departments d ON d.branch_id = b.id
JOIN racks r ON r.department_id = d.id
LEFT JOIN boxes bx ON bx.rack_id = r.id
LEFT JOIN ordners o ON o.box_id = bx.id
ORDER BY c.name, b.name, d.name, r.name, bx.name, o.name
`

type GetWarehouseTopologyRow struct {
	CompanyName    string      `json:"company_name"`
	BranchName     string      `json:"branch_name"`
	DepartmentName string      `json:"department_name"`
	RackID         uuid.UUID   `json:"rack_id"`
	RackName       string      `json:"rack_name"`
	BoxID          pgtype.UUID `json:"box_id"`
	BoxName        pgtype.Text `json:"box_name"`
	OrdnerID       pgtype.UUID `json:"ordner_id"`
	OrdnerName     pgtype.Text `json:"ordner_name"`
}

// Topology
func (q *Queries) GetWarehouseTopology(ctx context.Context) ([]GetWarehouseTopologyRow, error) {
	rows, err := q.db.Query(ctx, getWarehouseTopology)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWarehouseTopologyRow
	for rows.Next() {
		var i GetWarehouseTopologyRow
		if err := rows.Scan(
			&i.CompanyName,
			&i.BranchName,
			&i.DepartmentName,
			&i.RackID,
			&i.RackName,
			&i.BoxID,
			&i.BoxName,
			&i.OrdnerID,
			&i.OrdnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBoxesGlobal = `-- name: ListAllBoxesGlobal :many
SELECT bx.id, bx.rack_id, bx.name, bx.created_at, r.name as rack_name, d.name as department_name
FROM boxes bx
JOIN racks r ON bx.rack_id = r.id
JOIN departments d ON r.department_id = d.id
ORDER BY bx.name
`

type ListAllBoxesGlobalRow struct {
	ID             uuid.UUID          `json:"id"`
	RackID         uuid.UUID          `json:"rack_id"`
	Name           string             `json:"name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	RackName       string             `json:"rack_name"`
	DepartmentName string             `json:"department_name"`
}

func (q *Queries) ListAllBoxesGlobal(ctx context.Context) ([]ListAllBoxesGlobalRow, error) {
	rows, err := q.db.Query(ctx, listAllBoxesGlobal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllBoxesGlobalRow
	for rows.Next() {
		var i ListAllBoxesGlobalRow
		if err := rows.Scan(
			&i.ID,
			&i.RackID,
			&i.Name,
			&i.CreatedAt,
			&i.RackName,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBranchesGlobal = `-- name: ListAllBranchesGlobal :many
SELECT b.id, b.company_id, b.name, b.location, b.head_id, b.created_at, c.name as company_name 
FROM branches b
JOIN companies c ON b.company_id = c.id
ORDER BY b.name
`

type ListAllBranchesGlobalRow struct {
	ID          uuid.UUID          `json:"id"`
	CompanyID   uuid.UUID          `json:"company_id"`
	Name        string             `json:"name"`
	Location    pgtype.Text        `json:"location"`
	HeadID      pgtype.UUID        `json:"head_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CompanyName string             `json:"company_name"`
}

func (q *Queries) ListAllBranchesGlobal(ctx context.Context) ([]ListAllBranchesGlobalRow, error) {
	rows, err := q.db.Query(ctx, listAllBranchesGlobal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllBranchesGlobalRow
	for rows.Next() {
		var i ListAllBranchesGlobalRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Location,
			&i.HeadID,
			&i.CreatedAt,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDepartments = `-- name: ListAllDepartments :many
SELECT d.id, d.branch_id, d.name, d.head_id, d.created_at, b.name as branch_name 
FROM departments d
JOIN branches b ON d.branch_id = b.id
ORDER BY d.name
`

type ListAllDepartmentsRow struct {
	ID         uuid.UUID          `json:"id"`
	BranchID   uuid.UUID          `json:"branch_id"`
	Name       string             `json:"name"`
	HeadID     pgtype.UUID        `json:"head_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	BranchName string             `json:"branch_name"`
}

func (q *Queries) ListAllDepartments(ctx context.Context) ([]ListAllDepartmentsRow, error) {
	rows, err := q.db.Query(ctx, listAllDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllDepartmentsRow
	for rows.Next() {
		var i ListAllDepartmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.HeadID,
			&i.CreatedAt,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllOrdnersGlobal = `-- name: ListAllOrdnersGlobal :many
SELECT o.id, o.box_id, o.name, o.created_at, bx.name as box_name, r.name as rack_name
FROM ordners o
JOIN boxes bx ON o.box_id = bx.id
JOIN racks r ON bx.rack_id = r.id
ORDER BY o.name
`

type ListAllOrdnersGlobalRow struct {
	ID        uuid.UUID          `json:"id"`
	BoxID     uuid.UUID          `json:"box_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	BoxName   string             `json:"box_name"`
	RackName  string             `json:"rack_name"`
}

func (q *Queries) ListAllOrdnersGlobal(ctx context.Context) ([]ListAllOrdnersGlobalRow, error) {
	rows, err := q.db.Query(ctx, listAllOrdnersGlobal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllOrdnersGlobalRow
	for rows.Next() {
		var i ListAllOrdnersGlobalRow
		if err := rows.Scan(
			&i.ID,
			&i.BoxID,
			&i.Name,
			&i.CreatedAt,
			&i.BoxName,
			&i.RackName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRacksGlobal = `-- name: ListAllRacksGlobal :many
SELECT r.id, r.department_id, r.name, r.location_detail, r.created_at, d.name as department_name, b.name as branch_name
FROM racks r
JOIN departments d ON r.department_id = d.id
JOIN branches b ON d.branch_id = b.id
ORDER BY r.name
`

type ListAllRacksGlobalRow struct {
	ID             uuid.UUID          `json:"id"`
	DepartmentID   uuid.UUID          `json:"department_id"`
	Name           string             `json:"name"`
	LocationDetail pgtype.Text        `json:"location_detail"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DepartmentName string             `json:"department_name"`
	BranchName     string             `json:"branch_name"`
}

func (q *Queries) ListAllRacksGlobal(ctx context.Context) ([]ListAllRacksGlobalRow, error) {
	rows, err := q.db.Query(ctx, listAllRacksGlobal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllRacksGlobalRow
	for rows.Next() {
		var i ListAllRacksGlobalRow
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.Name,
			&i.LocationDetail,
			&i.CreatedAt,
			&i.DepartmentName,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoxes = `-- name: ListBoxes :many
SELECT id, rack_id, name, created_at FROM boxes WHERE rack_id = $1 ORDER BY name
`

// Boxes
func (q *Queries) ListBoxes(ctx context.Context, rackID uuid.UUID) ([]Box, error) {
	rows, err := q.db.Query(ctx, listBoxes, rackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Box
	for rows.Next() {
		var i Box
		if err := rows.Scan(
			&i.ID,
			&i.RackID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranches = `-- name: ListBranches :many
SELECT id, company_id, name, location, head_id, created_at FROM branches WHERE company_id = $1 ORDER BY name
`

// Branches
func (q *Queries) ListBranches(ctx context.Context, companyID uuid.UUID) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranches, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Location,
			&i.HeadID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, address, created_at, entity_id, npwp_status, location, status FROM companies ORDER BY name
`

// Companies
func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.CreatedAt,
			&i.EntityID,
			&i.NpwpStatus,
			&i.Location,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, branch_id, name, head_id, created_at FROM departments WHERE branch_id = $1 ORDER BY name
`

// Departments
func (q *Queries) ListDepartments(ctx context.Context, branchID uuid.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.HeadID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdners = `-- name: ListOrdners :many
SELECT id, box_id, name, created_at FROM ordners WHERE box_id = $1 ORDER BY name
`

// Ordners
func (q *Queries) ListOrdners(ctx context.Context, boxID uuid.UUID) ([]Ordner, error) {
	rows, err := q.db.Query(ctx, listOrdners, boxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ordner
	for rows.Next() {
		var i Ordner
		if err := rows.Scan(
			&i.ID,
			&i.BoxID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRacks = `-- name: ListRacks :many
SELECT id, department_id, name, location_detail, created_at FROM racks WHERE department_id = $1 ORDER BY name
`

// Racks
func (q *Queries) ListRacks(ctx context.Context, departmentID uuid.UUID) ([]Rack, error) {
	rows, err := q.db.Query(ctx, listRacks, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rack
	for rows.Next() {
		var i Rack
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.Name,
			&i.LocationDetail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetentionPolicies = `-- name: ListRetentionPolicies :many
SELECT id, name, description, retention_years, department_id, document_category, is_active, created_at, updated_at FROM retention_policies ORDER BY name
`

// Retention Policies
func (q *Queries) ListRetentionPolicies(ctx context.Context) ([]RetentionPolicy, error) {
	rows, err := q.db.Query(ctx, listRetentionPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetentionPolicy
	for rows.Next() {
		var i RetentionPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RetentionYears,
			&i.DepartmentID,
			&i.DocumentCategory,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRfidTags = `-- name: ListRfidTags :many
SELECT tag_id, document_id, status, assigned_at FROM rfid_tags ORDER BY assigned_at DESC
`

// RFID Tags
func (q *Queries) ListRfidTags(ctx context.Context) ([]RfidTag, error) {
	rows, err := q.db.Query(ctx, listRfidTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RfidTag
	for rows.Next() {
		var i RfidTag
		if err := rows.Scan(
			&i.TagID,
			&i.DocumentID,
			&i.Status,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, ldap_group FROM roles ORDER BY name
`

// Roles
func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LdapGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBox = `-- name: UpdateBox :one
UPDATE boxes SET name = $2
WHERE id = $1
RETURNING id, rack_id, name, created_at
`

type UpdateBoxParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateBox(ctx context.Context, arg UpdateBoxParams) (Box, error) {
	row := q.db.QueryRow(ctx, updateBox, arg.ID, arg.Name)
	var i Box
	err := row.Scan(
		&i.ID,
		&i.RackID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branches SET name = $2, location = $3, head_id = $4
WHERE id = $1
RETURNING id, company_id, name, location, head_id, created_at
`

type UpdateBranchParams struct {
	ID       uuid.UUID   `json:"id"`
	Name     string      `json:"name"`
	Location pgtype.Text `json:"location"`
	HeadID   pgtype.UUID `json:"head_id"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.ID,
		arg.Name,
		arg.Location,
		arg.HeadID,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Location,
		&i.HeadID,
		&i.CreatedAt,
	)
	return i, err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies SET 
    name = $2, 
    entity_id = $3, 
    npwp_status = $4, 
    location = $5, 
    status = $6, 
    address = $7
WHERE id = $1
RETURNING id, name, address, created_at, entity_id, npwp_status, location, status
`

type UpdateCompanyParams struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	EntityID   pgtype.Text `json:"entity_id"`
	NpwpStatus pgtype.Text `json:"npwp_status"`
	Location   pgtype.Text `json:"location"`
	Status     pgtype.Text `json:"status"`
	Address    pgtype.Text `json:"address"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.EntityID,
		arg.NpwpStatus,
		arg.Location,
		arg.Status,
		arg.Address,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.EntityID,
		&i.NpwpStatus,
		&i.Location,
		&i.Status,
	)
	return i, err
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments SET name = $2, head_id = $3
WHERE id = $1
RETURNING id, branch_id, name, head_id, created_at
`

type UpdateDepartmentParams struct {
	ID     uuid.UUID   `json:"id"`
	Name   string      `json:"name"`
	HeadID pgtype.UUID `json:"head_id"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment, arg.ID, arg.Name, arg.HeadID)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.HeadID,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrdner = `-- name: UpdateOrdner :one
UPDATE ordners SET name = $2
WHERE id = $1
RETURNING id, box_id, name, created_at
`

type UpdateOrdnerParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateOrdner(ctx context.Context, arg UpdateOrdnerParams) (Ordner, error) {
	row := q.db.QueryRow(ctx, updateOrdner, arg.ID, arg.Name)
	var i Ordner
	err := row.Scan(
		&i.ID,
		&i.BoxID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const updateRack = `-- name: UpdateRack :one
UPDATE racks SET name = $2, location_detail = $3
WHERE id = $1
RETURNING id, department_id, name, location_detail, created_at
`

type UpdateRackParams struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	LocationDetail pgtype.Text `json:"location_detail"`
}

func (q *Queries) UpdateRack(ctx context.Context, arg UpdateRackParams) (Rack, error) {
	row := q.db.QueryRow(ctx, updateRack, arg.ID, arg.Name, arg.LocationDetail)
	var i Rack
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Name,
		&i.LocationDetail,
		&i.CreatedAt,
	)
	return i, err
}

const updateRetentionPolicy = `-- name: UpdateRetentionPolicy :one
UPDATE retention_policies SET name = $2, description = $3, retention_years = $4, department_id = $5, document_category = $6
WHERE id = $1
RETURNING id, name, description, retention_years, department_id, document_category, is_active, created_at, updated_at
`

type UpdateRetentionPolicyParams struct {
	ID               uuid.UUID   `json:"id"`
	Name             string      `json:"name"`
	Description      pgtype.Text `json:"description"`
	RetentionYears   int32       `json:"retention_years"`
	DepartmentID     pgtype.UUID `json:"department_id"`
	DocumentCategory pgtype.Text `json:"document_category"`
}

func (q *Queries) UpdateRetentionPolicy(ctx context.Context, arg UpdateRetentionPolicyParams) (RetentionPolicy, error) {
	row := q.db.QueryRow(ctx, updateRetentionPolicy,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.RetentionYears,
		arg.DepartmentID,
		arg.DocumentCategory,
	)
	var i RetentionPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RetentionYears,
		&i.DepartmentID,
		&i.DocumentCategory,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRfidTagStatus = `-- name: UpdateRfidTagStatus :one
UPDATE rfid_tags SET status = $2
WHERE tag_id = $1
RETURNING tag_id, document_id, status, assigned_at
`

type UpdateRfidTagStatusParams struct {
	TagID  string `json:"tag_id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateRfidTagStatus(ctx context.Context, arg UpdateRfidTagStatusParams) (RfidTag, error) {
	row := q.db.QueryRow(ctx, updateRfidTagStatus, arg.TagID, arg.Status)
	var i RfidTag
	err := row.Scan(
		&i.TagID,
		&i.DocumentID,
		&i.Status,
		&i.AssignedAt,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles SET name = $2, description = $3
WHERE id = $1
RETURNING id, name, description, ldap_group
`

type UpdateRoleParams struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.ID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LdapGroup,
	)
	return i, err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
INSERT INTO system_settings (category, key, value, value_type, description, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (category, key) DO UPDATE
SET value = EXCLUDED.value, value_type = EXCLUDED.value_type, description = EXCLUDED.description, updated_by = EXCLUDED.updated_by, updated_at = NOW()
RETURNING id, category, key, value, value_type, description, updated_by, updated_at
`

type UpsertSystemSettingParams struct {
	Category    string      `json:"category"`
	Key         string      `json:"key"`
	Value       pgtype.Text `json:"value"`
	ValueType   pgtype.Text `json:"value_type"`
	Description pgtype.Text `json:"description"`
	UpdatedBy   pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertSystemSetting,
		arg.Category,
		arg.Key,
		arg.Value,
		arg.ValueType,
		arg.Description,
		arg.UpdatedBy,
	)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Key,
		&i.Value,
		&i.ValueType,
		&i.Description,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
