// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Details    []byte             `json:"details"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type BorrowRequest struct {
	ID         uuid.UUID          `json:"id"`
	DocumentID uuid.UUID          `json:"document_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Reason     string             `json:"reason"`
	Status     string             `json:"status"`
	BorrowDate pgtype.Timestamptz `json:"borrow_date"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
	ReturnDate pgtype.Timestamptz `json:"return_date"`
	ApprovedBy pgtype.UUID        `json:"approved_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Box struct {
	ID        uuid.UUID          `json:"id"`
	RackID    uuid.UUID          `json:"rack_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Branch struct {
	ID        uuid.UUID          `json:"id"`
	CompanyID uuid.UUID          `json:"company_id"`
	Name      string             `json:"name"`
	Location  pgtype.Text        `json:"location"`
	HeadID    pgtype.UUID        `json:"head_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Company struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Address   pgtype.Text        `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Department struct {
	ID        uuid.UUID          `json:"id"`
	BranchID  uuid.UUID          `json:"branch_id"`
	Name      string             `json:"name"`
	HeadID    pgtype.UUID        `json:"head_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	FileName       string             `json:"file_name"`
	FilePath       string             `json:"file_path"`
	FileSize       int64              `json:"file_size"`
	MimeType       string             `json:"mime_type"`
	Checksum       pgtype.Text        `json:"checksum"`
	CompanyID      uuid.UUID          `json:"company_id"`
	BranchID       uuid.UUID          `json:"branch_id"`
	DepartmentID   uuid.UUID          `json:"department_id"`
	RackID         pgtype.UUID        `json:"rack_id"`
	BoxID          pgtype.UUID        `json:"box_id"`
	OrdnerID       pgtype.UUID        `json:"ordner_id"`
	OwnerID        uuid.UUID          `json:"owner_id"`
	CurrentVersion int32              `json:"current_version"`
	Status         string             `json:"status"`
	Tags           []string           `json:"tags"`
	Metadata       []byte             `json:"metadata"`
	ExtractedText  pgtype.Text        `json:"extracted_text"`
	IsOcrProcessed pgtype.Bool        `json:"is_ocr_processed"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	BatchID        pgtype.UUID        `json:"batch_id"`
}

type DocumentRoleAccess struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	RoleID     int32     `json:"role_id"`
}

type DocumentVersion struct {
	ID         uuid.UUID          `json:"id"`
	DocumentID uuid.UUID          `json:"document_id"`
	Version    int32              `json:"version"`
	FilePath   string             `json:"file_path"`
	FileSize   int64              `json:"file_size"`
	ChangeNote pgtype.Text        `json:"change_note"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Ordner struct {
	ID        uuid.UUID          `json:"id"`
	BoxID     uuid.UUID          `json:"box_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProcessingBatch struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	TotalFiles     int32              `json:"total_files"`
	ProcessedFiles pgtype.Int4        `json:"processed_files"`
	Status         pgtype.Text        `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Rack struct {
	ID             uuid.UUID          `json:"id"`
	DepartmentID   uuid.UUID          `json:"department_id"`
	Name           string             `json:"name"`
	LocationDetail pgtype.Text        `json:"location_detail"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RfidTag struct {
	TagID      string             `json:"tag_id"`
	DocumentID uuid.UUID          `json:"document_id"`
	Status     string             `json:"status"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type Role struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	RoleID       int32              `json:"role_id"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Status       string             `json:"status"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	SignatureUrl pgtype.Text        `json:"signature_url"`
	// 6-digit transaction PIN for high-security approvals (L2)
	Pin pgtype.Text `json:"pin"`
}
