// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id, title, body, type, entity_type, entity_id, channel, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, user_id, title, body, type, entity_type, entity_id, channel, is_read, read_at, created_at, metadata
`

type CreateNotificationParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	Title      string      `json:"title"`
	Body       pgtype.Text `json:"body"`
	Type       string      `json:"type"`
	EntityType pgtype.Text `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Channel    pgtype.Text `json:"channel"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.Type,
		arg.EntityType,
		arg.EntityID,
		arg.Channel,
		arg.Metadata,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.Type,
		&i.EntityType,
		&i.EntityID,
		&i.Channel,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) FROM notifications 
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) GetUnreadCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, title, body, type, entity_type, entity_id, channel, is_read, read_at, created_at, metadata FROM notifications 
WHERE user_id = $1 
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.Type,
			&i.EntityType,
			&i.EntityID,
			&i.Channel,
			&i.IsRead,
			&i.ReadAt,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllAsRead = `-- name: MarkAllAsRead :exec
UPDATE notifications 
SET is_read = true, read_at = NOW() 
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllAsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllAsRead, userID)
	return err
}

const markAsRead = `-- name: MarkAsRead :exec
UPDATE notifications 
SET is_read = true, read_at = NOW() 
WHERE id = $1 AND user_id = $2
`

type MarkAsReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkAsRead(ctx context.Context, arg MarkAsReadParams) error {
	_, err := q.db.Exec(ctx, markAsRead, arg.ID, arg.UserID)
	return err
}
