// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBatch(ctx context.Context, arg CreateBatchParams) (ProcessingBatch, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetBatch(ctx context.Context, id uuid.UUID) (ProcessingBatch, error)
	GetDocument(ctx context.Context, id uuid.UUID) (Document, error)
	GetDocumentsByBatch(ctx context.Context, batchID pgtype.UUID) ([]Document, error)
	GetRoleIDByName(ctx context.Context, name string) (int32, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListDocumentsByDepartment(ctx context.Context, departmentID uuid.UUID) ([]Document, error)
	ListPendingUsers(ctx context.Context) ([]User, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateBatchProgress(ctx context.Context, id uuid.UUID) error
	UpdateDocumentOCR(ctx context.Context, arg UpdateDocumentOCRParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
