// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddManifestItem(ctx context.Context, arg AddManifestItemParams) (PhysicalManifestItem, error)
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	ApproveLoanRequestL1(ctx context.Context, arg ApproveLoanRequestL1Params) error
	ApproveTask(ctx context.Context, arg ApproveTaskParams) error
	ClearRolePermissions(ctx context.Context, roleID int32) error
	CountL1ApprovedLoans(ctx context.Context) (int64, error)
	CountOCRJobs(ctx context.Context) (int64, error)
	CountSsoSyncLogs(ctx context.Context) (int64, error)
	CountUserLoanRequests(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error)
	CreateApprovalTask(ctx context.Context, arg CreateApprovalTaskParams) (ApprovalWorkflow, error)
	CreateBatch(ctx context.Context, arg CreateBatchParams) (ProcessingBatch, error)
	CreateBox(ctx context.Context, arg CreateBoxParams) (Box, error)
	CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateDocumentCategory(ctx context.Context, arg CreateDocumentCategoryParams) (DocumentCategory, error)
	CreateDocumentType(ctx context.Context, arg CreateDocumentTypeParams) (DocumentType, error)
	CreateIntegrationNode(ctx context.Context, arg CreateIntegrationNodeParams) (IntegrationNode, error)
	CreateLoanExtension(ctx context.Context, arg CreateLoanExtensionParams) (LoanExtension, error)
	CreateLoanRequest(ctx context.Context, arg CreateLoanRequestParams) (LoanRequest, error)
	CreateLoanRequestItem(ctx context.Context, arg CreateLoanRequestItemParams) (LoanRequestItem, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOCRJob(ctx context.Context, arg CreateOCRJobParams) (OcrJob, error)
	CreateOrdner(ctx context.Context, arg CreateOrdnerParams) (Ordner, error)
	CreatePhysicalManifest(ctx context.Context, arg CreatePhysicalManifestParams) (PhysicalManifest, error)
	CreateRack(ctx context.Context, arg CreateRackParams) (Rack, error)
	CreateRetentionPolicy(ctx context.Context, arg CreateRetentionPolicyParams) (RetentionPolicy, error)
	CreateRfidTag(ctx context.Context, arg CreateRfidTagParams) (RfidTag, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSsoSyncLog(ctx context.Context, arg CreateSsoSyncLogParams) (SsoSyncLog, error)
	CreateStockItem(ctx context.Context, arg CreateStockItemParams) (StockOpnameItem, error)
	CreateStockMission(ctx context.Context, arg CreateStockMissionParams) (StockOpnameMission, error)
	CreateStockSession(ctx context.Context, arg CreateStockSessionParams) (StockOpnameSession, error)
	CreateSystemModule(ctx context.Context, arg CreateSystemModuleParams) (SystemModule, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateAllAnnouncements(ctx context.Context) error
	DeleteAnnouncement(ctx context.Context, id uuid.UUID) error
	DeleteBox(ctx context.Context, id uuid.UUID) error
	DeleteBranch(ctx context.Context, id uuid.UUID) error
	DeleteCompany(ctx context.Context, id uuid.UUID) error
	DeleteDepartment(ctx context.Context, id uuid.UUID) error
	DeleteDocumentCategory(ctx context.Context, id uuid.UUID) error
	DeleteDocumentType(ctx context.Context, id uuid.UUID) error
	DeleteIntegrationNode(ctx context.Context, id uuid.UUID) error
	DeleteOrdner(ctx context.Context, id uuid.UUID) error
	DeleteRack(ctx context.Context, id uuid.UUID) error
	DeleteRetentionPolicy(ctx context.Context, id uuid.UUID) error
	DeleteRole(ctx context.Context, id int32) error
	DeleteSystemModule(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	ExtendLoanRequestDueDate(ctx context.Context, arg ExtendLoanRequestDueDateParams) error
	FindEligibleBoxes(ctx context.Context, arg FindEligibleBoxesParams) ([]FindEligibleBoxesRow, error)
	GetActiveAnnouncement(ctx context.Context) (Announcement, error)
	GetActiveDocControllers(ctx context.Context) ([]GetActiveDocControllersRow, error)
	GetActivityLogsByEntity(ctx context.Context, arg GetActivityLogsByEntityParams) ([]GetActivityLogsByEntityRow, error)
	GetAnnouncement(ctx context.Context, id uuid.UUID) (Announcement, error)
	GetBatch(ctx context.Context, id uuid.UUID) (ProcessingBatch, error)
	GetBox(ctx context.Context, id uuid.UUID) (Box, error)
	GetBranch(ctx context.Context, id uuid.UUID) (Branch, error)
	GetBranches(ctx context.Context) ([]GetBranchesRow, error)
	GetCompanies(ctx context.Context) ([]GetCompaniesRow, error)
	GetCompany(ctx context.Context, id uuid.UUID) (Company, error)
	GetDailyStats(ctx context.Context) (GetDailyStatsRow, error)
	GetDepartment(ctx context.Context, id uuid.UUID) (Department, error)
	GetDepartments(ctx context.Context) ([]GetDepartmentsRow, error)
	GetDocument(ctx context.Context, id uuid.UUID) (GetDocumentRow, error)
	GetDocumentByShortID(ctx context.Context, dollar_1 pgtype.Text) (GetDocumentByShortIDRow, error)
	GetDocumentCategory(ctx context.Context, id uuid.UUID) (DocumentCategory, error)
	GetDocumentHierarchyCounts(ctx context.Context) ([]GetDocumentHierarchyCountsRow, error)
	GetDocumentLoanHistory(ctx context.Context, documentID uuid.UUID) ([]GetDocumentLoanHistoryRow, error)
	GetDocumentType(ctx context.Context, id uuid.UUID) (DocumentType, error)
	GetDocumentWithDetails(ctx context.Context, id uuid.UUID) (GetDocumentWithDetailsRow, error)
	GetDocumentsByBatch(ctx context.Context, batchID pgtype.UUID) ([]Document, error)
	GetDocumentsByTargetArea(ctx context.Context, name string) ([]GetDocumentsByTargetAreaRow, error)
	GetEmailTemplateBySlug(ctx context.Context, slug string) (EmailTemplate, error)
	GetIntakeStats(ctx context.Context) (GetIntakeStatsRow, error)
	GetIntegrationNode(ctx context.Context, id uuid.UUID) (IntegrationNode, error)
	GetIntegrationNodeByEndpoint(ctx context.Context, arg GetIntegrationNodeByEndpointParams) (IntegrationNode, error)
	GetIntegrationNodeByType(ctx context.Context, serviceType string) (IntegrationNode, error)
	GetLabelingStats(ctx context.Context) (GetLabelingStatsRow, error)
	GetLastSsoSyncLog(ctx context.Context) (SsoSyncLog, error)
	GetLatestApprovalTaskByEntity(ctx context.Context, arg GetLatestApprovalTaskByEntityParams) (ApprovalWorkflow, error)
	GetLoanExtension(ctx context.Context, id uuid.UUID) (GetLoanExtensionRow, error)
	GetLoanRequest(ctx context.Context, id uuid.UUID) (GetLoanRequestRow, error)
	GetLoanRequestItems(ctx context.Context, loanRequestID uuid.UUID) ([]GetLoanRequestItemsRow, error)
	GetManagerDailyStats(ctx context.Context, headID pgtype.UUID) (GetManagerDailyStatsRow, error)
	GetManagerRecentActivities(ctx context.Context, arg GetManagerRecentActivitiesParams) ([]GetManagerRecentActivitiesRow, error)
	GetManagerTopSubmitters(ctx context.Context, arg GetManagerTopSubmittersParams) ([]GetManagerTopSubmittersRow, error)
	GetManifest(ctx context.Context, id uuid.UUID) (GetManifestRow, error)
	GetManifestByNo(ctx context.Context, manifestNo string) (GetManifestByNoRow, error)
	GetManifestItems(ctx context.Context, manifestID uuid.UUID) ([]GetManifestItemsRow, error)
	GetManifestProgress(ctx context.Context, manifestID uuid.UUID) (GetManifestProgressRow, error)
	GetNextLoanRequestNo(ctx context.Context) (int32, error)
	GetOCRJobByEntity(ctx context.Context, arg GetOCRJobByEntityParams) (OcrJob, error)
	GetOrdner(ctx context.Context, id uuid.UUID) (Ordner, error)
	GetPendingCountsByType(ctx context.Context, approverID uuid.UUID) ([]GetPendingCountsByTypeRow, error)
	GetPendingLoanExtensionByLoanRequest(ctx context.Context, loanRequestID uuid.UUID) (LoanExtension, error)
	GetPriorityTasks(ctx context.Context, limit int32) ([]GetPriorityTasksRow, error)
	GetProfileByID(ctx context.Context, id uuid.UUID) (GetProfileByIDRow, error)
	GetRack(ctx context.Context, id uuid.UUID) (Rack, error)
	GetRecentActivities(ctx context.Context, limit int32) ([]GetRecentActivitiesRow, error)
	GetRfidTag(ctx context.Context, tagID string) (RfidTag, error)
	GetRole(ctx context.Context, id int32) (Role, error)
	GetRoleIDByName(ctx context.Context, name string) (int32, error)
	GetRolePermissions(ctx context.Context, roleID int32) ([]GetRolePermissionsRow, error)
	GetStagingStats(ctx context.Context) (GetStagingStatsRow, error)
	GetStockItemBySku(ctx context.Context, arg GetStockItemBySkuParams) (StockOpnameItem, error)
	GetStockMission(ctx context.Context, id uuid.UUID) (GetStockMissionRow, error)
	GetStockMissionStats(ctx context.Context) (GetStockMissionStatsRow, error)
	GetStockSession(ctx context.Context, id uuid.UUID) (StockOpnameSession, error)
	GetSystemModule(ctx context.Context, id string) (SystemModule, error)
	GetSystemSetting(ctx context.Context, arg GetSystemSettingParams) (SystemSetting, error)
	// System Settings
	GetSystemSettingsByCategory(ctx context.Context, category string) ([]SystemSetting, error)
	GetUnreadCount(ctx context.Context, userID uuid.UUID) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserDailyStats(ctx context.Context, ownerID uuid.UUID) (GetUserDailyStatsRow, error)
	GetUserLoanHistory(ctx context.Context, arg GetUserLoanHistoryParams) ([]GetUserLoanHistoryRow, error)
	GetUserPriorityTasks(ctx context.Context, arg GetUserPriorityTasksParams) ([]GetUserPriorityTasksRow, error)
	GetUserRecentActivities(ctx context.Context, arg GetUserRecentActivitiesParams) ([]GetUserRecentActivitiesRow, error)
	GetUsersForHierarchy(ctx context.Context) ([]GetUsersForHierarchyRow, error)
	GetWarehouseTopology(ctx context.Context) ([]GetWarehouseTopologyRow, error)
	ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ListActivityLogsRow, error)
	ListAllBoxesGlobal(ctx context.Context) ([]ListAllBoxesGlobalRow, error)
	ListAllBranchesGlobal(ctx context.Context) ([]ListAllBranchesGlobalRow, error)
	ListAllDepartments(ctx context.Context) ([]ListAllDepartmentsRow, error)
	ListAllLoanRequests(ctx context.Context, limit int32) ([]ListAllLoanRequestsRow, error)
	ListAllOrdnersGlobal(ctx context.Context) ([]ListAllOrdnersGlobalRow, error)
	ListAllRacksGlobal(ctx context.Context) ([]ListAllRacksGlobalRow, error)
	// Announcements
	ListAnnouncements(ctx context.Context) ([]Announcement, error)
	// Boxes
	ListBoxes(ctx context.Context, rackID uuid.UUID) ([]Box, error)
	// Branches
	ListBranches(ctx context.Context, companyID uuid.UUID) ([]Branch, error)
	// Companies
	ListCompanies(ctx context.Context) ([]Company, error)
	// Departments
	ListDepartments(ctx context.Context, branchID uuid.UUID) ([]Department, error)
	// Document Categories
	ListDocumentCategories(ctx context.Context) ([]DocumentCategory, error)
	// Document Types
	ListDocumentTypes(ctx context.Context) ([]ListDocumentTypesRow, error)
	ListDocumentsByDepartment(ctx context.Context, departmentID uuid.UUID) ([]Document, error)
	ListDocumentsForLabeling(ctx context.Context, status string) ([]ListDocumentsForLabelingRow, error)
	ListEmailTemplates(ctx context.Context) ([]EmailTemplate, error)
	ListIntegrationNodes(ctx context.Context) ([]IntegrationNode, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListOCRJobs(ctx context.Context, arg ListOCRJobsParams) ([]ListOCRJobsRow, error)
	// Ordners
	ListOrdners(ctx context.Context, boxID uuid.UUID) ([]Ordner, error)
	ListPendingDocumentsWithoutManifest(ctx context.Context) ([]ListPendingDocumentsWithoutManifestRow, error)
	ListPendingLoanExtensionsForApprover(ctx context.Context, approverID uuid.UUID) ([]ListPendingLoanExtensionsForApproverRow, error)
	ListPendingManifests(ctx context.Context) ([]ListPendingManifestsRow, error)
	ListPendingUsers(ctx context.Context) ([]User, error)
	ListPermissionsByRole(ctx context.Context, roleID int32) ([]ListPermissionsByRoleRow, error)
	// Racks
	ListRacks(ctx context.Context, departmentID uuid.UUID) ([]Rack, error)
	ListRecentDocuments(ctx context.Context, arg ListRecentDocumentsParams) ([]ListRecentDocumentsRow, error)
	ListRecentDocumentsByOwner(ctx context.Context, arg ListRecentDocumentsByOwnerParams) ([]ListRecentDocumentsByOwnerRow, error)
	// Retention Policies
	ListRetentionPolicies(ctx context.Context) ([]RetentionPolicy, error)
	// RFID Tags
	ListRfidTags(ctx context.Context) ([]RfidTag, error)
	// Roles
	ListRoles(ctx context.Context) ([]ListRolesRow, error)
	ListSsoSyncLogs(ctx context.Context, arg ListSsoSyncLogsParams) ([]SsoSyncLog, error)
	ListStagingManifests(ctx context.Context) ([]ListStagingManifestsRow, error)
	ListStockItemsBySession(ctx context.Context, sessionID uuid.UUID) ([]StockOpnameItem, error)
	ListStockMissions(ctx context.Context, arg ListStockMissionsParams) ([]ListStockMissionsRow, error)
	// System Modules & Permissions
	ListSystemModules(ctx context.Context) ([]SystemModule, error)
	ListUserLoanRequests(ctx context.Context, userID uuid.UUID) ([]ListUserLoanRequestsRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	ListUsersByRoles(ctx context.Context, dollar_1 []string) ([]ListUsersByRolesRow, error)
	MarkAllAsRead(ctx context.Context, userID uuid.UUID) error
	MarkAsRead(ctx context.Context, arg MarkAsReadParams) error
	RejectLoanRequest(ctx context.Context, arg RejectLoanRequestParams) error
	RejectLoanRequestL2(ctx context.Context, arg RejectLoanRequestL2Params) error
	RejectTask(ctx context.Context, arg RejectTaskParams) error
	ResetTaskToPending(ctx context.Context, arg ResetTaskToPendingParams) error
	SearchBoxes(ctx context.Context, dollar_1 pgtype.Text) ([]SearchBoxesRow, error)
	SearchDocuments(ctx context.Context, arg SearchDocumentsParams) ([]SearchDocumentsRow, error)
	UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error)
	UpdateBatchProgress(ctx context.Context, id uuid.UUID) error
	UpdateBox(ctx context.Context, arg UpdateBoxParams) (Box, error)
	UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
	UpdateCompanyLogo(ctx context.Context, arg UpdateCompanyLogoParams) error
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateDepartmentFloorPlan(ctx context.Context, arg UpdateDepartmentFloorPlanParams) (Department, error)
	UpdateDepartmentHead(ctx context.Context, arg UpdateDepartmentHeadParams) error
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error)
	UpdateDocumentCategory(ctx context.Context, arg UpdateDocumentCategoryParams) (DocumentCategory, error)
	UpdateDocumentIndexing(ctx context.Context, arg UpdateDocumentIndexingParams) error
	UpdateDocumentMetadata(ctx context.Context, arg UpdateDocumentMetadataParams) error
	UpdateDocumentOCR(ctx context.Context, arg UpdateDocumentOCRParams) error
	UpdateDocumentPhysicalStatus(ctx context.Context, arg UpdateDocumentPhysicalStatusParams) error
	UpdateDocumentPhysicalStatusBulk(ctx context.Context, arg UpdateDocumentPhysicalStatusBulkParams) error
	UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error
	UpdateDocumentType(ctx context.Context, arg UpdateDocumentTypeParams) (DocumentType, error)
	UpdateEmailTemplate(ctx context.Context, arg UpdateEmailTemplateParams) (EmailTemplate, error)
	UpdateIntegrationNodeConfig(ctx context.Context, arg UpdateIntegrationNodeConfigParams) (IntegrationNode, error)
	UpdateIntegrationNodeStatus(ctx context.Context, arg UpdateIntegrationNodeStatusParams) (IntegrationNode, error)
	UpdateLoanExtensionStatus(ctx context.Context, arg UpdateLoanExtensionStatusParams) error
	UpdateLoanRequestStatus(ctx context.Context, arg UpdateLoanRequestStatusParams) error
	UpdateManifestItemStatus(ctx context.Context, arg UpdateManifestItemStatusParams) error
	UpdateManifestItemStatusBulk(ctx context.Context, arg UpdateManifestItemStatusBulkParams) error
	UpdateManifestItemStatusByDocID(ctx context.Context, arg UpdateManifestItemStatusByDocIDParams) error
	UpdateManifestStatus(ctx context.Context, arg UpdateManifestStatusParams) error
	UpdateOrdner(ctx context.Context, arg UpdateOrdnerParams) (Ordner, error)
	UpdateRack(ctx context.Context, arg UpdateRackParams) (Rack, error)
	UpdateRackMapCoordinates(ctx context.Context, arg UpdateRackMapCoordinatesParams) (Rack, error)
	UpdateRackOverrideStatus(ctx context.Context, arg UpdateRackOverrideStatusParams) (Rack, error)
	UpdateRetentionPolicy(ctx context.Context, arg UpdateRetentionPolicyParams) (RetentionPolicy, error)
	UpdateRfidTagStatus(ctx context.Context, arg UpdateRfidTagStatusParams) (RfidTag, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateSsoSyncLog(ctx context.Context, arg UpdateSsoSyncLogParams) (SsoSyncLog, error)
	UpdateStockItemQuantity(ctx context.Context, arg UpdateStockItemQuantityParams) error
	UpdateStockItemResolution(ctx context.Context, arg UpdateStockItemResolutionParams) error
	UpdateStockMissionStatus(ctx context.Context, arg UpdateStockMissionStatusParams) error
	UpdateStockSessionStatus(ctx context.Context, arg UpdateStockSessionStatusParams) error
	UpdateStockSessionSummary(ctx context.Context, arg UpdateStockSessionSummaryParams) error
	UpdateSystemModule(ctx context.Context, arg UpdateSystemModuleParams) (SystemModule, error)
	UpdateTaskStatusByEntity(ctx context.Context, arg UpdateTaskStatusByEntityParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserDepartment(ctx context.Context, arg UpdateUserDepartmentParams) error
	UpdateUserMFASecret(ctx context.Context, arg UpdateUserMFASecretParams) error
	UpdateUserPIN(ctx context.Context, arg UpdateUserPINParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
	UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error)
}

var _ Querier = (*Queries)(nil)
