// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sso_sync.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSsoSyncLog = `-- name: CreateSsoSyncLog :one
INSERT INTO sso_sync_logs (
    provider, status, started_at
) VALUES (
    $1, $2, $3
) RETURNING id, provider, status, users_synced, groups_synced, errors, error_details, started_at, completed_at, created_at
`

type CreateSsoSyncLogParams struct {
	Provider  string             `json:"provider"`
	Status    string             `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) CreateSsoSyncLog(ctx context.Context, arg CreateSsoSyncLogParams) (SsoSyncLog, error) {
	row := q.db.QueryRow(ctx, createSsoSyncLog, arg.Provider, arg.Status, arg.StartedAt)
	var i SsoSyncLog
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Status,
		&i.UsersSynced,
		&i.GroupsSynced,
		&i.Errors,
		&i.ErrorDetails,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLastSsoSyncLog = `-- name: GetLastSsoSyncLog :one
SELECT id, provider, status, users_synced, groups_synced, errors, error_details, started_at, completed_at, created_at FROM sso_sync_logs
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastSsoSyncLog(ctx context.Context) (SsoSyncLog, error) {
	row := q.db.QueryRow(ctx, getLastSsoSyncLog)
	var i SsoSyncLog
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Status,
		&i.UsersSynced,
		&i.GroupsSynced,
		&i.Errors,
		&i.ErrorDetails,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSsoSyncLogs = `-- name: ListSsoSyncLogs :many
SELECT id, provider, status, users_synced, groups_synced, errors, error_details, started_at, completed_at, created_at FROM sso_sync_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSsoSyncLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSsoSyncLogs(ctx context.Context, arg ListSsoSyncLogsParams) ([]SsoSyncLog, error) {
	rows, err := q.db.Query(ctx, listSsoSyncLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SsoSyncLog
	for rows.Next() {
		var i SsoSyncLog
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Status,
			&i.UsersSynced,
			&i.GroupsSynced,
			&i.Errors,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSsoSyncLog = `-- name: UpdateSsoSyncLog :one
UPDATE sso_sync_logs
SET 
    status = $2,
    users_synced = $3,
    groups_synced = $4,
    errors = $5,
    error_details = $6,
    completed_at = $7
WHERE id = $1
RETURNING id, provider, status, users_synced, groups_synced, errors, error_details, started_at, completed_at, created_at
`

type UpdateSsoSyncLogParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       string             `json:"status"`
	UsersSynced  pgtype.Int4        `json:"users_synced"`
	GroupsSynced pgtype.Int4        `json:"groups_synced"`
	Errors       pgtype.Int4        `json:"errors"`
	ErrorDetails []byte             `json:"error_details"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateSsoSyncLog(ctx context.Context, arg UpdateSsoSyncLogParams) (SsoSyncLog, error) {
	row := q.db.QueryRow(ctx, updateSsoSyncLog,
		arg.ID,
		arg.Status,
		arg.UsersSynced,
		arg.GroupsSynced,
		arg.Errors,
		arg.ErrorDetails,
		arg.CompletedAt,
	)
	var i SsoSyncLog
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Status,
		&i.UsersSynced,
		&i.GroupsSynced,
		&i.Errors,
		&i.ErrorDetails,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countSsoSyncLogs = `-- name: CountSsoSyncLogs :one
SELECT COUNT(*) FROM sso_sync_logs
`

func (q *Queries) CountSsoSyncLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSsoSyncLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}
