// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStockItem = `-- name: CreateStockItem :one
INSERT INTO stock_opname_items (id, session_id, document_id, sku_code, item_name, system_qty, physical_qty, status, location_name, sub_location, scanned_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
RETURNING id, session_id, document_id, sku_code, item_name, system_qty, physical_qty, variance, status, location_name, sub_location, resolution, resolution_note, scanned_at
`

type CreateStockItemParams struct {
	SessionID    uuid.UUID   `json:"session_id"`
	DocumentID   pgtype.UUID `json:"document_id"`
	SkuCode      pgtype.Text `json:"sku_code"`
	ItemName     pgtype.Text `json:"item_name"`
	SystemQty    int32       `json:"system_qty"`
	PhysicalQty  int32       `json:"physical_qty"`
	Status       string      `json:"status"`
	LocationName pgtype.Text `json:"location_name"`
	SubLocation  pgtype.Text `json:"sub_location"`
}

func (q *Queries) CreateStockItem(ctx context.Context, arg CreateStockItemParams) (StockOpnameItem, error) {
	row := q.db.QueryRow(ctx, createStockItem,
		arg.SessionID,
		arg.DocumentID,
		arg.SkuCode,
		arg.ItemName,
		arg.SystemQty,
		arg.PhysicalQty,
		arg.Status,
		arg.LocationName,
		arg.SubLocation,
	)
	var i StockOpnameItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentID,
		&i.SkuCode,
		&i.ItemName,
		&i.SystemQty,
		&i.PhysicalQty,
		&i.Variance,
		&i.Status,
		&i.LocationName,
		&i.SubLocation,
		&i.Resolution,
		&i.ResolutionNote,
		&i.ScannedAt,
	)
	return i, err
}

const createStockMission = `-- name: CreateStockMission :one
INSERT INTO stock_opname_missions (id, session_id, title, description, assigned_to, target_area, status, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, 'pending', NOW())
RETURNING id, session_id, title, description, assigned_to, target_area, status, completed_at, created_at
`

type CreateStockMissionParams struct {
	SessionID   pgtype.UUID `json:"session_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	AssignedTo  uuid.UUID   `json:"assigned_to"`
	TargetArea  pgtype.Text `json:"target_area"`
}

func (q *Queries) CreateStockMission(ctx context.Context, arg CreateStockMissionParams) (StockOpnameMission, error) {
	row := q.db.QueryRow(ctx, createStockMission,
		arg.SessionID,
		arg.Title,
		arg.Description,
		arg.AssignedTo,
		arg.TargetArea,
	)
	var i StockOpnameMission
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Title,
		&i.Description,
		&i.AssignedTo,
		&i.TargetArea,
		&i.Status,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStockSession = `-- name: CreateStockSession :one
INSERT INTO stock_opname_sessions (id, session_no, branch_id, department_id, conducted_by, status, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, 'in_progress', NOW(), NOW())
RETURNING id, session_no, branch_id, department_id, conducted_by, total_matched, total_on_loan, total_missing, total_extra, status, approved_by, approved_at, resolution_note, created_at, updated_at
`

type CreateStockSessionParams struct {
	SessionNo    string      `json:"session_no"`
	BranchID     pgtype.UUID `json:"branch_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
	ConductedBy  uuid.UUID   `json:"conducted_by"`
}

func (q *Queries) CreateStockSession(ctx context.Context, arg CreateStockSessionParams) (StockOpnameSession, error) {
	row := q.db.QueryRow(ctx, createStockSession,
		arg.SessionNo,
		arg.BranchID,
		arg.DepartmentID,
		arg.ConductedBy,
	)
	var i StockOpnameSession
	err := row.Scan(
		&i.ID,
		&i.SessionNo,
		&i.BranchID,
		&i.DepartmentID,
		&i.ConductedBy,
		&i.TotalMatched,
		&i.TotalOnLoan,
		&i.TotalMissing,
		&i.TotalExtra,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentsByTargetArea = `-- name: GetDocumentsByTargetArea :many
SELECT d.id, d.title, d.file_name, r.name as rack_name, b.name as box_name
FROM documents d
LEFT JOIN racks r ON d.rack_id = r.id
LEFT JOIN boxes b ON d.box_id = b.id
WHERE r.name ILIKE $1 OR b.name ILIKE $1 OR $1 = 'all'
`

type GetDocumentsByTargetAreaRow struct {
	ID       uuid.UUID   `json:"id"`
	Title    string      `json:"title"`
	FileName pgtype.Text `json:"file_name"`
	RackName pgtype.Text `json:"rack_name"`
	BoxName  pgtype.Text `json:"box_name"`
}

func (q *Queries) GetDocumentsByTargetArea(ctx context.Context, name string) ([]GetDocumentsByTargetAreaRow, error) {
	rows, err := q.db.Query(ctx, getDocumentsByTargetArea, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentsByTargetAreaRow
	for rows.Next() {
		var i GetDocumentsByTargetAreaRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FileName,
			&i.RackName,
			&i.BoxName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockItemBySku = `-- name: GetStockItemBySku :one
SELECT id, session_id, document_id, sku_code, item_name, system_qty, physical_qty, variance, status, location_name, sub_location, resolution, resolution_note, scanned_at FROM stock_opname_items WHERE session_id = $1 AND sku_code = $2 LIMIT 1
`

type GetStockItemBySkuParams struct {
	SessionID uuid.UUID   `json:"session_id"`
	SkuCode   pgtype.Text `json:"sku_code"`
}

func (q *Queries) GetStockItemBySku(ctx context.Context, arg GetStockItemBySkuParams) (StockOpnameItem, error) {
	row := q.db.QueryRow(ctx, getStockItemBySku, arg.SessionID, arg.SkuCode)
	var i StockOpnameItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DocumentID,
		&i.SkuCode,
		&i.ItemName,
		&i.SystemQty,
		&i.PhysicalQty,
		&i.Variance,
		&i.Status,
		&i.LocationName,
		&i.SubLocation,
		&i.Resolution,
		&i.ResolutionNote,
		&i.ScannedAt,
	)
	return i, err
}

const getStockMission = `-- name: GetStockMission :one
SELECT 
    m.id, m.session_id, m.title, m.description, m.assigned_to, m.target_area, m.status, m.completed_at, m.created_at,
    u.full_name as assigned_operator_name,
    s.session_no, s.status as session_status
FROM stock_opname_missions m
JOIN users u ON m.assigned_to = u.id
LEFT JOIN stock_opname_sessions s ON m.session_id = s.id
WHERE m.id = $1
`

type GetStockMissionRow struct {
	ID                   uuid.UUID          `json:"id"`
	SessionID            pgtype.UUID        `json:"session_id"`
	Title                string             `json:"title"`
	Description          pgtype.Text        `json:"description"`
	AssignedTo           uuid.UUID          `json:"assigned_to"`
	TargetArea           pgtype.Text        `json:"target_area"`
	Status               pgtype.Text        `json:"status"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	AssignedOperatorName string             `json:"assigned_operator_name"`
	SessionNo            pgtype.Text        `json:"session_no"`
	SessionStatus        pgtype.Text        `json:"session_status"`
}

func (q *Queries) GetStockMission(ctx context.Context, id uuid.UUID) (GetStockMissionRow, error) {
	row := q.db.QueryRow(ctx, getStockMission, id)
	var i GetStockMissionRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Title,
		&i.Description,
		&i.AssignedTo,
		&i.TargetArea,
		&i.Status,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.AssignedOperatorName,
		&i.SessionNo,
		&i.SessionStatus,
	)
	return i, err
}

const getStockMissionStats = `-- name: GetStockMissionStats :one
SELECT 
    COUNT(CASE WHEN status = 'pending' THEN 1 END)::int as pending_missions,
    COUNT(CASE WHEN status = 'in_progress' THEN 1 END)::int as active_missions,
    COALESCE(
        ROUND(
            (COUNT(CASE WHEN status = 'completed' THEN 1 END)::float / 
             NULLIF(COUNT(*), 0) * 100)::numeric, 1
        )::float, 0.0
    )::float as accuracy_rate
FROM stock_opname_missions
`

type GetStockMissionStatsRow struct {
	PendingMissions int32   `json:"pending_missions"`
	ActiveMissions  int32   `json:"active_missions"`
	AccuracyRate    float64 `json:"accuracy_rate"`
}

func (q *Queries) GetStockMissionStats(ctx context.Context) (GetStockMissionStatsRow, error) {
	row := q.db.QueryRow(ctx, getStockMissionStats)
	var i GetStockMissionStatsRow
	err := row.Scan(&i.PendingMissions, &i.ActiveMissions, &i.AccuracyRate)
	return i, err
}

const getStockSession = `-- name: GetStockSession :one
SELECT id, session_no, branch_id, department_id, conducted_by, total_matched, total_on_loan, total_missing, total_extra, status, approved_by, approved_at, resolution_note, created_at, updated_at FROM stock_opname_sessions WHERE id = $1
`

func (q *Queries) GetStockSession(ctx context.Context, id uuid.UUID) (StockOpnameSession, error) {
	row := q.db.QueryRow(ctx, getStockSession, id)
	var i StockOpnameSession
	err := row.Scan(
		&i.ID,
		&i.SessionNo,
		&i.BranchID,
		&i.DepartmentID,
		&i.ConductedBy,
		&i.TotalMatched,
		&i.TotalOnLoan,
		&i.TotalMissing,
		&i.TotalExtra,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStockItemsBySession = `-- name: ListStockItemsBySession :many
SELECT id, session_id, document_id, sku_code, item_name, system_qty, physical_qty, variance, status, location_name, sub_location, resolution, resolution_note, scanned_at FROM stock_opname_items WHERE session_id = $1 ORDER BY scanned_at DESC
`

func (q *Queries) ListStockItemsBySession(ctx context.Context, sessionID uuid.UUID) ([]StockOpnameItem, error) {
	rows, err := q.db.Query(ctx, listStockItemsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockOpnameItem
	for rows.Next() {
		var i StockOpnameItem
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DocumentID,
			&i.SkuCode,
			&i.ItemName,
			&i.SystemQty,
			&i.PhysicalQty,
			&i.Variance,
			&i.Status,
			&i.LocationName,
			&i.SubLocation,
			&i.Resolution,
			&i.ResolutionNote,
			&i.ScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMissions = `-- name: ListStockMissions :many
SELECT 
    m.id, m.session_id, m.title, m.description, m.assigned_to, m.target_area, m.status, m.completed_at, m.created_at,
    u.full_name as assigned_operator_name,
    COALESCE(s.session_no, '') as session_no,
    COALESCE(s.status, '') as session_status
FROM stock_opname_missions m
JOIN users u ON m.assigned_to = u.id
LEFT JOIN stock_opname_sessions s ON m.session_id = s.id
ORDER BY m.created_at DESC
LIMIT $1 OFFSET $2
`

type ListStockMissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListStockMissionsRow struct {
	ID                   uuid.UUID          `json:"id"`
	SessionID            pgtype.UUID        `json:"session_id"`
	Title                string             `json:"title"`
	Description          pgtype.Text        `json:"description"`
	AssignedTo           uuid.UUID          `json:"assigned_to"`
	TargetArea           pgtype.Text        `json:"target_area"`
	Status               pgtype.Text        `json:"status"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	AssignedOperatorName string             `json:"assigned_operator_name"`
	SessionNo            string             `json:"session_no"`
	SessionStatus        string             `json:"session_status"`
}

func (q *Queries) ListStockMissions(ctx context.Context, arg ListStockMissionsParams) ([]ListStockMissionsRow, error) {
	rows, err := q.db.Query(ctx, listStockMissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockMissionsRow
	for rows.Next() {
		var i ListStockMissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Title,
			&i.Description,
			&i.AssignedTo,
			&i.TargetArea,
			&i.Status,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.AssignedOperatorName,
			&i.SessionNo,
			&i.SessionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStockItemQuantity = `-- name: UpdateStockItemQuantity :exec
UPDATE stock_opname_items
SET physical_qty = $2, status = $3, scanned_at = NOW()
WHERE id = $1
`

type UpdateStockItemQuantityParams struct {
	ID          uuid.UUID `json:"id"`
	PhysicalQty int32     `json:"physical_qty"`
	Status      string    `json:"status"`
}

func (q *Queries) UpdateStockItemQuantity(ctx context.Context, arg UpdateStockItemQuantityParams) error {
	_, err := q.db.Exec(ctx, updateStockItemQuantity, arg.ID, arg.PhysicalQty, arg.Status)
	return err
}

const updateStockItemResolution = `-- name: UpdateStockItemResolution :exec
UPDATE stock_opname_items
SET resolution = $2, resolution_note = $3
WHERE id = $1
`

type UpdateStockItemResolutionParams struct {
	ID             uuid.UUID   `json:"id"`
	Resolution     pgtype.Text `json:"resolution"`
	ResolutionNote pgtype.Text `json:"resolution_note"`
}

func (q *Queries) UpdateStockItemResolution(ctx context.Context, arg UpdateStockItemResolutionParams) error {
	_, err := q.db.Exec(ctx, updateStockItemResolution, arg.ID, arg.Resolution, arg.ResolutionNote)
	return err
}

const updateStockMissionStatus = `-- name: UpdateStockMissionStatus :exec
UPDATE stock_opname_missions 
SET status = $2, completed_at = CASE WHEN $2 = 'completed' THEN NOW() ELSE completed_at END
WHERE id = $1
`

type UpdateStockMissionStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateStockMissionStatus(ctx context.Context, arg UpdateStockMissionStatusParams) error {
	_, err := q.db.Exec(ctx, updateStockMissionStatus, arg.ID, arg.Status)
	return err
}

const updateStockSessionStatus = `-- name: UpdateStockSessionStatus :exec
UPDATE stock_opname_sessions
SET status = $2, approved_by = $3, approved_at = CASE WHEN $2 = 'approved' THEN NOW() ELSE approved_at END, resolution_note = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateStockSessionStatusParams struct {
	ID             uuid.UUID   `json:"id"`
	Status         string      `json:"status"`
	ApprovedBy     pgtype.UUID `json:"approved_by"`
	ResolutionNote pgtype.Text `json:"resolution_note"`
}

func (q *Queries) UpdateStockSessionStatus(ctx context.Context, arg UpdateStockSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updateStockSessionStatus,
		arg.ID,
		arg.Status,
		arg.ApprovedBy,
		arg.ResolutionNote,
	)
	return err
}

const updateStockSessionSummary = `-- name: UpdateStockSessionSummary :exec
UPDATE stock_opname_sessions
SET total_matched = $2, total_on_loan = $3, total_missing = $4, total_extra = $5, updated_at = NOW()
WHERE id = $1
`

type UpdateStockSessionSummaryParams struct {
	ID           uuid.UUID   `json:"id"`
	TotalMatched pgtype.Int4 `json:"total_matched"`
	TotalOnLoan  pgtype.Int4 `json:"total_on_loan"`
	TotalMissing pgtype.Int4 `json:"total_missing"`
	TotalExtra   pgtype.Int4 `json:"total_extra"`
}

func (q *Queries) UpdateStockSessionSummary(ctx context.Context, arg UpdateStockSessionSummaryParams) error {
	_, err := q.db.Exec(ctx, updateStockSessionSummary,
		arg.ID,
		arg.TotalMatched,
		arg.TotalOnLoan,
		arg.TotalMissing,
		arg.TotalExtra,
	)
	return err
}
