// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password_hash, full_name, role_id, department_id, status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, email, password_hash, full_name, role_id, department_id, is_active, created_at, updated_at, status, avatar_url, signature_url, pin
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
	RoleID       int32       `json:"role_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.RoleID,
		arg.DepartmentID,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.RoleID,
		&i.DepartmentID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.AvatarUrl,
		&i.SignatureUrl,
		&i.Pin,
	)
	return i, err
}

const getRoleIDByName = `-- name: GetRoleIDByName :one
SELECT id FROM roles WHERE name = $1 LIMIT 1
`

func (q *Queries) GetRoleIDByName(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, getRoleIDByName, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u.email, u.password_hash, u.full_name, u.role_id, u.department_id, u.is_active, u.created_at, u.updated_at, u.status, u.avatar_url, u.signature_url, r.name as role_name 
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	RoleID       int32              `json:"role_id"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Status       string             `json:"status"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	SignatureUrl pgtype.Text        `json:"signature_url"`
	RoleName     pgtype.Text        `json:"role_name"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.RoleID,
		&i.DepartmentID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.AvatarUrl,
		&i.SignatureUrl,
		&i.RoleName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, role_id, department_id, is_active, created_at, updated_at, status, avatar_url, signature_url, pin FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.RoleID,
		&i.DepartmentID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.AvatarUrl,
		&i.SignatureUrl,
		&i.Pin,
	)
	return i, err
}

const listPendingUsers = `-- name: ListPendingUsers :many
SELECT id, email, password_hash, full_name, role_id, department_id, is_active, created_at, updated_at, status, avatar_url, signature_url, pin FROM users WHERE status = 'pending' ORDER BY created_at ASC
`

func (q *Queries) ListPendingUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listPendingUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.RoleID,
			&i.DepartmentID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.AvatarUrl,
			&i.SignatureUrl,
			&i.Pin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, full_name, role_id, department_id, is_active, created_at, updated_at, status, avatar_url, signature_url, pin FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.RoleID,
			&i.DepartmentID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.AvatarUrl,
			&i.SignatureUrl,
			&i.Pin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPIN = `-- name: UpdateUserPIN :exec
UPDATE users SET pin = $2 WHERE id = $1
`

type UpdateUserPINParams struct {
	ID  uuid.UUID   `json:"id"`
	Pin pgtype.Text `json:"pin"`
}

func (q *Queries) UpdateUserPIN(ctx context.Context, arg UpdateUserPINParams) error {
	_, err := q.db.Exec(ctx, updateUserPIN, arg.ID, arg.Pin)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users 
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, full_name, role_id, department_id, is_active, created_at, updated_at, status, avatar_url, signature_url, pin
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.RoleID,
		&i.DepartmentID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.AvatarUrl,
		&i.SignatureUrl,
		&i.Pin,
	)
	return i, err
}
