// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password_hash, full_name, role_id, department_id, status, avatar_url, signature_url, is_mfa_enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, email, password_hash, full_name, role_id, department_id, is_active, created_at, updated_at, status, avatar_url, signature_url, pin, pin_status, pin_failed_attempts, pin_locked_until, pin_updated_at, is_mfa_enabled, mfa_secret
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
	RoleID       int32       `json:"role_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
	Status       string      `json:"status"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	SignatureUrl pgtype.Text `json:"signature_url"`
	IsMfaEnabled pgtype.Bool `json:"is_mfa_enabled"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.RoleID,
		arg.DepartmentID,
		arg.Status,
		arg.AvatarUrl,
		arg.SignatureUrl,
		arg.IsMfaEnabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.RoleID,
		&i.DepartmentID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.AvatarUrl,
		&i.SignatureUrl,
		&i.Pin,
		&i.PinStatus,
		&i.PinFailedAttempts,
		&i.PinLockedUntil,
		&i.PinUpdatedAt,
		&i.IsMfaEnabled,
		&i.MfaSecret,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT 
    u.id, u.email, u.password_hash, u.full_name, u.role_id, u.department_id, u.is_active, u.created_at, u.updated_at, u.status, u.avatar_url, u.signature_url, u.pin, u.pin_status, u.pin_failed_attempts, u.pin_locked_until, u.pin_updated_at, u.is_mfa_enabled, u.mfa_secret, 
    r.name as role_name,
    d.name as department_name,
    b.name as branch_name,
    c.name as company_name
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
LEFT JOIN departments d ON u.department_id = d.id
LEFT JOIN branches b ON d.branch_id = b.id
LEFT JOIN companies c ON b.company_id = c.id
WHERE u.id = $1 LIMIT 1
`

type GetProfileByIDRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	FullName          string             `json:"full_name"`
	RoleID            int32              `json:"role_id"`
	DepartmentID      pgtype.UUID        `json:"department_id"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Status            string             `json:"status"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	SignatureUrl      pgtype.Text        `json:"signature_url"`
	Pin               pgtype.Text        `json:"pin"`
	PinStatus         pgtype.Text        `json:"pin_status"`
	PinFailedAttempts pgtype.Int4        `json:"pin_failed_attempts"`
	PinLockedUntil    pgtype.Timestamptz `json:"pin_locked_until"`
	PinUpdatedAt      pgtype.Timestamptz `json:"pin_updated_at"`
	IsMfaEnabled      pgtype.Bool        `json:"is_mfa_enabled"`
	MfaSecret         pgtype.Text        `json:"mfa_secret"`
	RoleName          pgtype.Text        `json:"role_name"`
	DepartmentName    pgtype.Text        `json:"department_name"`
	BranchName        pgtype.Text        `json:"branch_name"`
	CompanyName       pgtype.Text        `json:"company_name"`
}

func (q *Queries) GetProfileByID(ctx context.Context, id uuid.UUID) (GetProfileByIDRow, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i GetProfileByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.RoleID,
		&i.DepartmentID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.AvatarUrl,
		&i.SignatureUrl,
		&i.Pin,
		&i.PinStatus,
		&i.PinFailedAttempts,
		&i.PinLockedUntil,
		&i.PinUpdatedAt,
		&i.IsMfaEnabled,
		&i.MfaSecret,
		&i.RoleName,
		&i.DepartmentName,
		&i.BranchName,
		&i.CompanyName,
	)
	return i, err
}

const getRoleIDByName = `-- name: GetRoleIDByName :one
SELECT id FROM roles WHERE name = $1 LIMIT 1
`

func (q *Queries) GetRoleIDByName(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, getRoleIDByName, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u.email, u.password_hash, u.full_name, u.role_id, u.department_id, u.is_active, u.created_at, u.updated_at, u.status, u.avatar_url, u.signature_url, u.pin, u.pin_status, u.pin_failed_attempts, u.pin_locked_until, u.pin_updated_at, u.is_mfa_enabled, u.mfa_secret, r.name as role_name 
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	FullName          string             `json:"full_name"`
	RoleID            int32              `json:"role_id"`
	DepartmentID      pgtype.UUID        `json:"department_id"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Status            string             `json:"status"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	SignatureUrl      pgtype.Text        `json:"signature_url"`
	Pin               pgtype.Text        `json:"pin"`
	PinStatus         pgtype.Text        `json:"pin_status"`
	PinFailedAttempts pgtype.Int4        `json:"pin_failed_attempts"`
	PinLockedUntil    pgtype.Timestamptz `json:"pin_locked_until"`
	PinUpdatedAt      pgtype.Timestamptz `json:"pin_updated_at"`
	IsMfaEnabled      pgtype.Bool        `json:"is_mfa_enabled"`
	MfaSecret         pgtype.Text        `json:"mfa_secret"`
	RoleName          pgtype.Text        `json:"role_name"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.RoleID,
		&i.DepartmentID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.AvatarUrl,
		&i.SignatureUrl,
		&i.Pin,
		&i.PinStatus,
		&i.PinFailedAttempts,
		&i.PinLockedUntil,
		&i.PinUpdatedAt,
		&i.IsMfaEnabled,
		&i.MfaSecret,
		&i.RoleName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.email, u.password_hash, u.full_name, u.role_id, u.department_id, u.is_active, u.created_at, u.updated_at, u.status, u.avatar_url, u.signature_url, u.pin, u.pin_status, u.pin_failed_attempts, u.pin_locked_until, u.pin_updated_at, u.is_mfa_enabled, u.mfa_secret, r.name as role_name 
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	FullName          string             `json:"full_name"`
	RoleID            int32              `json:"role_id"`
	DepartmentID      pgtype.UUID        `json:"department_id"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Status            string             `json:"status"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	SignatureUrl      pgtype.Text        `json:"signature_url"`
	Pin               pgtype.Text        `json:"pin"`
	PinStatus         pgtype.Text        `json:"pin_status"`
	PinFailedAttempts pgtype.Int4        `json:"pin_failed_attempts"`
	PinLockedUntil    pgtype.Timestamptz `json:"pin_locked_until"`
	PinUpdatedAt      pgtype.Timestamptz `json:"pin_updated_at"`
	IsMfaEnabled      pgtype.Bool        `json:"is_mfa_enabled"`
	MfaSecret         pgtype.Text        `json:"mfa_secret"`
	RoleName          pgtype.Text        `json:"role_name"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.RoleID,
		&i.DepartmentID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.AvatarUrl,
		&i.SignatureUrl,
		&i.Pin,
		&i.PinStatus,
		&i.PinFailedAttempts,
		&i.PinLockedUntil,
		&i.PinUpdatedAt,
		&i.IsMfaEnabled,
		&i.MfaSecret,
		&i.RoleName,
	)
	return i, err
}

const listPendingUsers = `-- name: ListPendingUsers :many
SELECT id, email, password_hash, full_name, role_id, department_id, is_active, created_at, updated_at, status, avatar_url, signature_url, pin, pin_status, pin_failed_attempts, pin_locked_until, pin_updated_at, is_mfa_enabled, mfa_secret FROM users WHERE status = 'pending' ORDER BY created_at ASC
`

func (q *Queries) ListPendingUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listPendingUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.RoleID,
			&i.DepartmentID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.AvatarUrl,
			&i.SignatureUrl,
			&i.Pin,
			&i.PinStatus,
			&i.PinFailedAttempts,
			&i.PinLockedUntil,
			&i.PinUpdatedAt,
			&i.IsMfaEnabled,
			&i.MfaSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.email, u.password_hash, u.full_name, u.role_id, u.department_id, u.is_active, u.created_at, u.updated_at, u.status, u.avatar_url, u.signature_url, u.pin, u.pin_status, u.pin_failed_attempts, u.pin_locked_until, u.pin_updated_at, u.is_mfa_enabled, u.mfa_secret, r.name as role_name 
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
ORDER BY u.created_at DESC
`

type ListUsersRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	FullName          string             `json:"full_name"`
	RoleID            int32              `json:"role_id"`
	DepartmentID      pgtype.UUID        `json:"department_id"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Status            string             `json:"status"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	SignatureUrl      pgtype.Text        `json:"signature_url"`
	Pin               pgtype.Text        `json:"pin"`
	PinStatus         pgtype.Text        `json:"pin_status"`
	PinFailedAttempts pgtype.Int4        `json:"pin_failed_attempts"`
	PinLockedUntil    pgtype.Timestamptz `json:"pin_locked_until"`
	PinUpdatedAt      pgtype.Timestamptz `json:"pin_updated_at"`
	IsMfaEnabled      pgtype.Bool        `json:"is_mfa_enabled"`
	MfaSecret         pgtype.Text        `json:"mfa_secret"`
	RoleName          pgtype.Text        `json:"role_name"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.RoleID,
			&i.DepartmentID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.AvatarUrl,
			&i.SignatureUrl,
			&i.Pin,
			&i.PinStatus,
			&i.PinFailedAttempts,
			&i.PinLockedUntil,
			&i.PinUpdatedAt,
			&i.IsMfaEnabled,
			&i.MfaSecret,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, full_name = $3, role_id = $4, department_id = $5, status = $6, 
    avatar_url = $7, signature_url = $8, is_mfa_enabled = $9, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, full_name, role_id, department_id, is_active, created_at, updated_at, status, avatar_url, signature_url, pin, pin_status, pin_failed_attempts, pin_locked_until, pin_updated_at, is_mfa_enabled, mfa_secret
`

type UpdateUserParams struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	FullName     string      `json:"full_name"`
	RoleID       int32       `json:"role_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
	Status       string      `json:"status"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	SignatureUrl pgtype.Text `json:"signature_url"`
	IsMfaEnabled pgtype.Bool `json:"is_mfa_enabled"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FullName,
		arg.RoleID,
		arg.DepartmentID,
		arg.Status,
		arg.AvatarUrl,
		arg.SignatureUrl,
		arg.IsMfaEnabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.RoleID,
		&i.DepartmentID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.AvatarUrl,
		&i.SignatureUrl,
		&i.Pin,
		&i.PinStatus,
		&i.PinFailedAttempts,
		&i.PinLockedUntil,
		&i.PinUpdatedAt,
		&i.IsMfaEnabled,
		&i.MfaSecret,
	)
	return i, err
}

const updateUserMFASecret = `-- name: UpdateUserMFASecret :exec
UPDATE users SET mfa_secret = $2, is_mfa_enabled = $3 WHERE id = $1
`

type UpdateUserMFASecretParams struct {
	ID           uuid.UUID   `json:"id"`
	MfaSecret    pgtype.Text `json:"mfa_secret"`
	IsMfaEnabled pgtype.Bool `json:"is_mfa_enabled"`
}

func (q *Queries) UpdateUserMFASecret(ctx context.Context, arg UpdateUserMFASecretParams) error {
	_, err := q.db.Exec(ctx, updateUserMFASecret, arg.ID, arg.MfaSecret, arg.IsMfaEnabled)
	return err
}

const updateUserPIN = `-- name: UpdateUserPIN :exec
UPDATE users SET pin = $2 WHERE id = $1
`

type UpdateUserPINParams struct {
	ID  uuid.UUID   `json:"id"`
	Pin pgtype.Text `json:"pin"`
}

func (q *Queries) UpdateUserPIN(ctx context.Context, arg UpdateUserPINParams) error {
	_, err := q.db.Exec(ctx, updateUserPIN, arg.ID, arg.Pin)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users 
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, full_name, role_id, department_id, is_active, created_at, updated_at, status, avatar_url, signature_url, pin, pin_status, pin_failed_attempts, pin_locked_until, pin_updated_at, is_mfa_enabled, mfa_secret
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.RoleID,
		&i.DepartmentID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.AvatarUrl,
		&i.SignatureUrl,
		&i.Pin,
		&i.PinStatus,
		&i.PinFailedAttempts,
		&i.PinLockedUntil,
		&i.PinUpdatedAt,
		&i.IsMfaEnabled,
		&i.MfaSecret,
	)
	return i, err
}
