// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warehouse.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLabelingStats = `-- name: GetLabelingStats :one
SELECT 
    COUNT(*) FILTER (WHERE status = 'digitized') as waiting_count,
    COUNT(*) FILTER (WHERE status = 'labeled') as printed_count,
    COUNT(*) FILTER (WHERE status = 'archived') as stored_count
FROM physical_manifest_items
`

type GetLabelingStatsRow struct {
	WaitingCount int64 `json:"waiting_count"`
	PrintedCount int64 `json:"printed_count"`
	StoredCount  int64 `json:"stored_count"`
}

func (q *Queries) GetLabelingStats(ctx context.Context) (GetLabelingStatsRow, error) {
	row := q.db.QueryRow(ctx, getLabelingStats)
	var i GetLabelingStatsRow
	err := row.Scan(&i.WaitingCount, &i.PrintedCount, &i.StoredCount)
	return i, err
}

const listDocumentsForLabeling = `-- name: ListDocumentsForLabeling :many
SELECT 
    d.id as document_id,
    d.title,
    dept.name as department_name,
    m.manifest_no,
    mi.status as manifest_item_status,
    d.physical_status,
    d.created_at
FROM documents d
JOIN physical_manifest_items mi ON d.id = mi.document_id
JOIN physical_manifests m ON mi.manifest_id = m.id
LEFT JOIN departments dept ON d.department_id = dept.id
WHERE mi.status = $1
ORDER BY d.created_at DESC
`

type ListDocumentsForLabelingRow struct {
	DocumentID         uuid.UUID          `json:"document_id"`
	Title              string             `json:"title"`
	DepartmentName     pgtype.Text        `json:"department_name"`
	ManifestNo         string             `json:"manifest_no"`
	ManifestItemStatus string             `json:"manifest_item_status"`
	PhysicalStatus     pgtype.Text        `json:"physical_status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDocumentsForLabeling(ctx context.Context, status string) ([]ListDocumentsForLabelingRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsForLabeling, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsForLabelingRow
	for rows.Next() {
		var i ListDocumentsForLabelingRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.Title,
			&i.DepartmentName,
			&i.ManifestNo,
			&i.ManifestItemStatus,
			&i.PhysicalStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentPhysicalStatusBulk = `-- name: UpdateDocumentPhysicalStatusBulk :exec
UPDATE documents
SET physical_status = $2, updated_at = NOW()
WHERE id = ANY($1::uuid[])
`

type UpdateDocumentPhysicalStatusBulkParams struct {
	Column1        []uuid.UUID `json:"column_1"`
	PhysicalStatus pgtype.Text `json:"physical_status"`
}

func (q *Queries) UpdateDocumentPhysicalStatusBulk(ctx context.Context, arg UpdateDocumentPhysicalStatusBulkParams) error {
	_, err := q.db.Exec(ctx, updateDocumentPhysicalStatusBulk, arg.Column1, arg.PhysicalStatus)
	return err
}

const updateManifestItemStatusBulk = `-- name: UpdateManifestItemStatusBulk :exec
UPDATE physical_manifest_items
SET status = $2, verified_at = NOW()
WHERE document_id = ANY($1::uuid[])
`

type UpdateManifestItemStatusBulkParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Status  string      `json:"status"`
}

func (q *Queries) UpdateManifestItemStatusBulk(ctx context.Context, arg UpdateManifestItemStatusBulkParams) error {
	_, err := q.db.Exec(ctx, updateManifestItemStatusBulk, arg.Column1, arg.Status)
	return err
}
