// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warehouse.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findEligibleBoxes = `-- name: FindEligibleBoxes :many
SELECT 
    b.id, b.rack_id, b.name, b.created_at, b.max_docs_capacity, b.current_docs_count, 
    r.name as rack_name, 
    r.location_detail,
    d.name as department_name
FROM boxes b
JOIN racks r ON b.rack_id = r.id
JOIN departments d ON r.department_id = d.id
WHERE r.department_id = $1
  AND r.is_full_override = FALSE
  AND (r.allowed_category_ids IS NULL OR array_length(r.allowed_category_ids, 1) IS NULL OR $2::uuid = ANY(r.allowed_category_ids))
  AND b.current_docs_count < b.max_docs_capacity
ORDER BY (b.max_docs_capacity - b.current_docs_count) DESC
LIMIT 5
`

type FindEligibleBoxesParams struct {
	DepartmentID uuid.UUID `json:"department_id"`
	CategoryID   uuid.UUID `json:"category_id"`
}

type FindEligibleBoxesRow struct {
	ID               uuid.UUID          `json:"id"`
	RackID           uuid.UUID          `json:"rack_id"`
	Name             string             `json:"name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	MaxDocsCapacity  pgtype.Int4        `json:"max_docs_capacity"`
	CurrentDocsCount pgtype.Int4        `json:"current_docs_count"`
	RackName         string             `json:"rack_name"`
	LocationDetail   pgtype.Text        `json:"location_detail"`
	DepartmentName   string             `json:"department_name"`
}

func (q *Queries) FindEligibleBoxes(ctx context.Context, arg FindEligibleBoxesParams) ([]FindEligibleBoxesRow, error) {
	rows, err := q.db.Query(ctx, findEligibleBoxes, arg.DepartmentID, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEligibleBoxesRow
	for rows.Next() {
		var i FindEligibleBoxesRow
		if err := rows.Scan(
			&i.ID,
			&i.RackID,
			&i.Name,
			&i.CreatedAt,
			&i.MaxDocsCapacity,
			&i.CurrentDocsCount,
			&i.RackName,
			&i.LocationDetail,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLabelingStats = `-- name: GetLabelingStats :one
SELECT 
    COUNT(*) FILTER (WHERE status = 'digitized') as waiting_count,
    COUNT(*) FILTER (WHERE status = 'labeled') as printed_count,
    COUNT(*) FILTER (WHERE status = 'archived') as stored_count
FROM physical_manifest_items
`

type GetLabelingStatsRow struct {
	WaitingCount int64 `json:"waiting_count"`
	PrintedCount int64 `json:"printed_count"`
	StoredCount  int64 `json:"stored_count"`
}

func (q *Queries) GetLabelingStats(ctx context.Context) (GetLabelingStatsRow, error) {
	row := q.db.QueryRow(ctx, getLabelingStats)
	var i GetLabelingStatsRow
	err := row.Scan(&i.WaitingCount, &i.PrintedCount, &i.StoredCount)
	return i, err
}

const listDocumentsForLabeling = `-- name: ListDocumentsForLabeling :many
SELECT 
    d.id as document_id,
    d.title,
    dept.name as department_name,
    m.manifest_no,
    mi.status as manifest_item_status,
    d.physical_status,
    d.created_at,
    bx.name as box_name
FROM documents d
JOIN physical_manifest_items mi ON d.id = mi.document_id
JOIN physical_manifests m ON mi.manifest_id = m.id
LEFT JOIN departments dept ON d.department_id = dept.id
LEFT JOIN boxes bx ON d.box_id = bx.id
WHERE mi.status = $1
ORDER BY d.created_at DESC
`

type ListDocumentsForLabelingRow struct {
	DocumentID         uuid.UUID          `json:"document_id"`
	Title              string             `json:"title"`
	DepartmentName     pgtype.Text        `json:"department_name"`
	ManifestNo         string             `json:"manifest_no"`
	ManifestItemStatus string             `json:"manifest_item_status"`
	PhysicalStatus     pgtype.Text        `json:"physical_status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	BoxName            pgtype.Text        `json:"box_name"`
}

func (q *Queries) ListDocumentsForLabeling(ctx context.Context, status string) ([]ListDocumentsForLabelingRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsForLabeling, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsForLabelingRow
	for rows.Next() {
		var i ListDocumentsForLabelingRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.Title,
			&i.DepartmentName,
			&i.ManifestNo,
			&i.ManifestItemStatus,
			&i.PhysicalStatus,
			&i.CreatedAt,
			&i.BoxName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBoxes = `-- name: SearchBoxes :many
SELECT 
    bx.id, bx.name, r.name as rack_name, d.name as department_name,
    c.name as company_name, b.name as branch_name,
    r.location_detail
FROM boxes bx
JOIN racks r ON bx.rack_id = r.id
JOIN departments d ON r.department_id = d.id
JOIN branches b ON d.branch_id = b.id
JOIN companies c ON b.company_id = c.id
WHERE bx.name ILIKE '%' || $1 || '%' 
   OR r.name ILIKE '%' || $1 || '%'
ORDER BY bx.name
LIMIT 20
`

type SearchBoxesRow struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	RackName       string      `json:"rack_name"`
	DepartmentName string      `json:"department_name"`
	CompanyName    string      `json:"company_name"`
	BranchName     string      `json:"branch_name"`
	LocationDetail pgtype.Text `json:"location_detail"`
}

func (q *Queries) SearchBoxes(ctx context.Context, dollar_1 pgtype.Text) ([]SearchBoxesRow, error) {
	rows, err := q.db.Query(ctx, searchBoxes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBoxesRow
	for rows.Next() {
		var i SearchBoxesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RackName,
			&i.DepartmentName,
			&i.CompanyName,
			&i.BranchName,
			&i.LocationDetail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentPhysicalStatusBulk = `-- name: UpdateDocumentPhysicalStatusBulk :exec
UPDATE documents
SET 
    physical_status = $2, 
    box_id = COALESCE(NULLIF($3::text, '')::uuid, box_id),
    updated_at = NOW()
WHERE id = ANY($1::uuid[])
`

type UpdateDocumentPhysicalStatusBulkParams struct {
	Column1        []uuid.UUID `json:"column_1"`
	PhysicalStatus pgtype.Text `json:"physical_status"`
	BoxID          string      `json:"box_id"`
}

func (q *Queries) UpdateDocumentPhysicalStatusBulk(ctx context.Context, arg UpdateDocumentPhysicalStatusBulkParams) error {
	_, err := q.db.Exec(ctx, updateDocumentPhysicalStatusBulk, arg.Column1, arg.PhysicalStatus, arg.BoxID)
	return err
}

const updateManifestItemStatusBulk = `-- name: UpdateManifestItemStatusBulk :exec
UPDATE physical_manifest_items
SET status = $2, verified_at = NOW()
WHERE document_id = ANY($1::uuid[])
`

type UpdateManifestItemStatusBulkParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Status  string      `json:"status"`
}

func (q *Queries) UpdateManifestItemStatusBulk(ctx context.Context, arg UpdateManifestItemStatusBulkParams) error {
	_, err := q.db.Exec(ctx, updateManifestItemStatusBulk, arg.Column1, arg.Status)
	return err
}
